apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: redis-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: redis-secret
    envs:
      - redis-dev.env
