kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

generators:
  - juicer-prod-gen.yaml

namespace: prod

# namePrefix: prod-

configMapGenerator:
  - name: juicer-conf
    envs:
      - juicer-prod.conf
