apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: postgres-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: postgres-superuser-secret
    type: kubernetes.io/basic-auth
    envs:
      - basic-auth.env
  - metadata:
      name: postgres-user-secret
    type: kubernetes.io/basic-auth
    envs:
      - basic-auth.env
