architecture: standalone

image:
  tag: 15.3.0-debian-11-r17

auth:
  enablePostgresUser: true
  database: juicer

primary:
  persistence:
    size: 4Gi
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
