version: v1.3.1

dsn: postgres://test:test@pg:5432/test?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: https://dev-dankop.xyz/kratos/
    cors:
      enabled: true
      debug: true
      allow_credentials: true
      options_passthrough: true
      max_age: 0
      allowed_origins:
        - https://dev-dankop.xyz
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
        - HEAD
      allowed_headers:
        - Content-Type
        - Authorization
        - Cookie
        - Origin
        - X-Session-Token
        - Accept
      exposed_headers:
        - Content-Type
        - Set-Cookie
        - Accept
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: https://dev-dankop.xyz
  allowed_return_urls:
    - https://dev-dankop.xyz
    - https://dev-dankop.xyz/dashboard
    - https://dev-dankop.xyz/auth/login
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_host: api.pwnedpasswords.com
        haveibeenpwned_enabled: true
        max_breaches: 0
        ignore_network_errors: true
        min_password_length: 8
        identifier_similarity_check_enabled: true
    profile:
      enabled: true
    link:
      enabled: true
      config:
        lifespan: 15m
    code:
      enabled: true
      config:
        lifespan: 15m
    totp:
      enabled: true
      config:
        issuer: dev-dankop.xyz
    lookup_secret:
      enabled: true
    oidc:
      enabled: true
      config:
        base_redirect_uri: https://dev-dankop.xyz/kratos/

  flows:
    error:
      ui_url: https://dev-dankop.xyz/error
    settings:
      ui_url: https://dev-dankop.xyz/dashboard/account
      privileged_session_max_age: 1m
      required_aal: highest_available
    recovery:
      enabled: true
      ui_url: https://dev-dankop.xyz/auth/recovery
      use: code
      after:
        default_browser_return_url: https://dev-dankop.xyz/auth/login
        hooks:
          - hook: revoke_active_sessions
    verification:
      enabled: true
      ui_url: https://dev-dankop.xyz/auth/verification
      use: code
      after:
        default_browser_return_url: https://dev-dankop.xyz/auth/login
    logout:
      after:
        default_browser_return_url: https://dev-dankop.xyz
    login:
      ui_url: https://dev-dankop.xyz/auth/login
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: require_verified_address
        oidc:
          default_browser_return_url: https://juicer-dev.xyz
    registration:
      enable_legacy_one_step: true
      ui_url: https://dev-dankop.xyz/auth/registration
      lifespan: 10m
      after:
        default_browser_return_url: https://dev-dankop.xyz/auth/login
        password:
          default_browser_return_url: https://dev-dankop.xyz/auth/login
          # hooks:
          #   - hook: web_hook
          #     config:
          #       method: POST
          #       # @TODO LATER
          #       # url: http://juicer-api:1337/api/v1/webhooks/kratos/registration_after_password
          #       url: https://juicer.co/api/v1/webhooks/kratos/registration_after_password
          #       body: file:///etc/config/kratos/hooks/registration.after.password.jsonnet
          #       can_interrupt: false
          #       response:
          #         ignore: false
          #         parse: false
        oidc:
          default_browser_return_url: https://dev-dankop.xyz
          hooks:
            - hook: session
            # - hook: web_hook
            #   config:
            #     method: POST
            #     # @TODO LATER
            #     # url: http://juicer-api:1337/api/v1/webhooks/kratos/registration_after_oidc
            #     url: https://juicer.co/api/v1/webhooks/kratos/registration_after_oidc
            #     body: file:///etc/config/kratos/hooks/registration.after.oidc.jsonnet
            #     can_interrupt: false
            #     response:
            #       ignore: false
            #       parse: false

secrets:
  cookie:
    - v3Ry_s3Cr3t_tExT

session:
  whoami:
    required_aal: aal1
  lifespan: 24h
  cookie:
    domain: dev-dankop.xyz
    same_site: Lax
    path: /

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 1
    salt_length: 16
    key_length: 32

identity:
  default_schema_id: customer
  schemas:
    - id: customer
      url: file:///etc/config/kratos/schemas/customer.identity.schema.json
    - id: employee
      url: file:///etc/config/kratos/schemas/employee.identity.schema.json

courier:
  message_retries: 5
  smtp:
    connection_uri: smtp://mailpit:1025?disable_starttls=true
    from_name: juicer
    from_address: juicer@juicer.xyz
  # template_override_path: /etc/config/kratos/courier-templates
  # templates:
  #   verification:
  #     valid:
  #       email:
  #         subject: file:///etc/config/kratos/courier-templates/verification/valid/email.subject.tmpl
  #         body:
  #           html: file:///etc/config/kratos/courier-templates/verification/valid/email.body.tmpl
  #           plaintext: file:///etc/config/kratos/courier-templates/verification/valid/email.body.plaintext.tmpl
  #     invalid:
  #       email:
  #         subject: file:///etc/config/kratos/courier-templates/verification/invalid/email.subject.tmpl
  #         body:
  #           html: file:///etc/config/kratos/courier-templates/verification/invalid/email.body.tmpl
  #           plaintext: file:///etc/config/kratos/courier-templates/verification/invalid/email.body.plaintext.tmpl
  #   recovery:
  #     valid:
  #       email:
  #         subject: file:///etc/config/kratos/courier-templates/recovery/valid/email.subject.tmpl
  #         body:
  #           html: file:///etc/config/kratos/courier-templates/recovery/valid/email.body.tmpl
  #           plaintext: file:///etc/config/kratos/courier-templates/recovery/valid/email.body.plaintext.tmpl
  #     invalid:
  #       email:
  #         subject: file:///etc/config/kratos/courier-templates/recovery/invalid/email.subject.tmpl
  #         body:
  #           html: file:///etc/config/kratos/courier-templates/recovery/invalid/email.body.tmpl
  #           plaintext: file:///etc/config/kratos/courier-templates/recovery/invalid/email.body.plaintext.tmpl
  #   recovery_code:
  #     valid:
  #       email:
  #         subject: file:///etc/config/kratos/courier-templates/recovery_code/valid/email.subject.tmpl
  #         body:
  #           html: file:///etc/config/kratos/courier-templates/recovery_code/valid/email.body.tmpl
  #           plaintext: file:///etc/config/kratos/courier-templates/recovery_code/valid/email.body.plaintext.tmpl
  #     invalid:
  #       email:
  #         subject: file:///etc/config/kratos/courier-templates/recovery_code/invalid/email.subject.tmpl
  #         body:
  #           html: file:///etc/config/kratos/courier-templates/recovery_code/invalid/email.body.tmpl
  #           plaintext: file:///etc/config/kratos/courier-templates/recovery_code/invalid/email.body.plaintext.tmpl
  #   verification_code:
  #     valid:
  #       email:
  #         subject: file:///etc/config/kratos/courier-templates/verification_code/valid/email.subject.tmpl
  #         body:
  #           html: file:///etc/config/kratos/courier-templates/verification_code/valid/email.body.tmpl
  #           plaintext: file:///etc/config/kratos/courier-templates/verification_code/valid/email.body.plaintext.tmpl
  #     invalid:
  #       email:
  #         subject: file:///etc/config/kratos/courier-templates/verification_code/invalid/email.subject.tmpl
  #         body:
  #           html: file:///etc/config/kratos/courier-templates/verification_code/invalid/email.body.tmpl
  #           plaintext: file:///etc/config/kratos/courier-templates/verification_code/invalid/email.body.plaintext.tmpl

log:
  level: debug
  format: json
  leak_sensitive_values: true
