// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: proto/juicer/juicer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*Message_Error
	//	*Message_Echo
	//	*Message_ClientConnected
	//	*Message_ClientDisconnected
	//	*Message_HubInfo
	//	*Message_MatchFound
	//	*Message_SeekingCount
	//	*Message_SeekGame
	//	*Message_CancelSeekGame
	Event isMessage_Event `protobuf_oneof:"event"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetEvent() isMessage_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *Message) GetError() *Error {
	if x, ok := x.GetEvent().(*Message_Error); ok {
		return x.Error
	}
	return nil
}

func (x *Message) GetEcho() *Echo {
	if x, ok := x.GetEvent().(*Message_Echo); ok {
		return x.Echo
	}
	return nil
}

func (x *Message) GetClientConnected() *ClientConnected {
	if x, ok := x.GetEvent().(*Message_ClientConnected); ok {
		return x.ClientConnected
	}
	return nil
}

func (x *Message) GetClientDisconnected() *ClientDisconnected {
	if x, ok := x.GetEvent().(*Message_ClientDisconnected); ok {
		return x.ClientDisconnected
	}
	return nil
}

func (x *Message) GetHubInfo() *HubInfo {
	if x, ok := x.GetEvent().(*Message_HubInfo); ok {
		return x.HubInfo
	}
	return nil
}

func (x *Message) GetMatchFound() *MatchFound {
	if x, ok := x.GetEvent().(*Message_MatchFound); ok {
		return x.MatchFound
	}
	return nil
}

func (x *Message) GetSeekingCount() *SeekingCount {
	if x, ok := x.GetEvent().(*Message_SeekingCount); ok {
		return x.SeekingCount
	}
	return nil
}

func (x *Message) GetSeekGame() *SeekGame {
	if x, ok := x.GetEvent().(*Message_SeekGame); ok {
		return x.SeekGame
	}
	return nil
}

func (x *Message) GetCancelSeekGame() *CancelSeekGame {
	if x, ok := x.GetEvent().(*Message_CancelSeekGame); ok {
		return x.CancelSeekGame
	}
	return nil
}

type isMessage_Event interface {
	isMessage_Event()
}

type Message_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type Message_Echo struct {
	Echo *Echo `protobuf:"bytes,2,opt,name=echo,proto3,oneof"`
}

type Message_ClientConnected struct {
	ClientConnected *ClientConnected `protobuf:"bytes,3,opt,name=client_connected,json=clientConnected,proto3,oneof"`
}

type Message_ClientDisconnected struct {
	ClientDisconnected *ClientDisconnected `protobuf:"bytes,4,opt,name=client_disconnected,json=clientDisconnected,proto3,oneof"`
}

type Message_HubInfo struct {
	HubInfo *HubInfo `protobuf:"bytes,5,opt,name=hub_info,json=hubInfo,proto3,oneof"`
}

type Message_MatchFound struct {
	MatchFound *MatchFound `protobuf:"bytes,6,opt,name=match_found,json=matchFound,proto3,oneof"`
}

type Message_SeekingCount struct {
	SeekingCount *SeekingCount `protobuf:"bytes,7,opt,name=seeking_count,json=seekingCount,proto3,oneof"`
}

type Message_SeekGame struct {
	SeekGame *SeekGame `protobuf:"bytes,8,opt,name=seek_game,json=seekGame,proto3,oneof"`
}

type Message_CancelSeekGame struct {
	CancelSeekGame *CancelSeekGame `protobuf:"bytes,9,opt,name=cancel_seek_game,json=cancelSeekGame,proto3,oneof"`
}

func (*Message_Error) isMessage_Event() {}

func (*Message_Echo) isMessage_Event() {}

func (*Message_ClientConnected) isMessage_Event() {}

func (*Message_ClientDisconnected) isMessage_Event() {}

func (*Message_HubInfo) isMessage_Event() {}

func (*Message_MatchFound) isMessage_Event() {}

func (*Message_SeekingCount) isMessage_Event() {}

func (*Message_SeekGame) isMessage_Event() {}

func (*Message_CancelSeekGame) isMessage_Event() {}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{2}
}

func (x *Echo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientConnected) Reset() {
	*x = ClientConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnected) ProtoMessage() {}

func (x *ClientConnected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnected.ProtoReflect.Descriptor instead.
func (*ClientConnected) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{3}
}

func (x *ClientConnected) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClientDisconnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientDisconnected) Reset() {
	*x = ClientDisconnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnected) ProtoMessage() {}

func (x *ClientDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnected.ProtoReflect.Descriptor instead.
func (*ClientDisconnected) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{4}
}

func (x *ClientDisconnected) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HubInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lobby   int32 `protobuf:"varint,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	Rooms   int32 `protobuf:"varint,2,opt,name=rooms,proto3" json:"rooms,omitempty"`
	Playing int32 `protobuf:"varint,3,opt,name=playing,proto3" json:"playing,omitempty"`
}

func (x *HubInfo) Reset() {
	*x = HubInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubInfo) ProtoMessage() {}

func (x *HubInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubInfo.ProtoReflect.Descriptor instead.
func (*HubInfo) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{5}
}

func (x *HubInfo) GetLobby() int32 {
	if x != nil {
		return x.Lobby
	}
	return 0
}

func (x *HubInfo) GetRooms() int32 {
	if x != nil {
		return x.Rooms
	}
	return 0
}

func (x *HubInfo) GetPlaying() int32 {
	if x != nil {
		return x.Playing
	}
	return 0
}

type MatchFound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{6}
}

func (x *MatchFound) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MatchFound) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type SeekingCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SeekingCount) Reset() {
	*x = SeekingCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekingCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekingCount) ProtoMessage() {}

func (x *SeekingCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekingCount.ProtoReflect.Descriptor instead.
func (*SeekingCount) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{7}
}

func (x *SeekingCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SeekGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameMode string `protobuf:"bytes,1,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
}

func (x *SeekGame) Reset() {
	*x = SeekGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekGame) ProtoMessage() {}

func (x *SeekGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekGame.ProtoReflect.Descriptor instead.
func (*SeekGame) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{8}
}

func (x *SeekGame) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

type CancelSeekGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelSeekGame) Reset() {
	*x = CancelSeekGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSeekGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSeekGame) ProtoMessage() {}

func (x *CancelSeekGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSeekGame.ProtoReflect.Descriptor instead.
func (*CancelSeekGame) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{9}
}

var File_proto_juicer_juicer_proto protoreflect.FileDescriptor

var file_proto_juicer_juicer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x75, 0x69, 0x63, 0x65, 0x72, 0x2f, 0x6a,
	0x75, 0x69, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0xe5, 0x03, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1e,
	0x0a, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x12, 0x40,
	0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x12, 0x49, 0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x08, 0x68,
	0x75, 0x62, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x48, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x07, 0x68, 0x75,
	0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x37, 0x0a, 0x0d, 0x73, 0x65, 0x65, 0x6b,
	0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x65, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x65, 0x65, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2b, 0x0a, 0x09, 0x73, 0x65, 0x65, 0x6b, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x65, 0x6b, 0x47, 0x61,
	0x6d, 0x65, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x3e,
	0x0a, 0x10, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x73, 0x65, 0x65, 0x6b, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x53, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0e,
	0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x07,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x04, 0x45, 0x63,
	0x68, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x21, 0x0a, 0x0f,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x24, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4f, 0x0a, 0x07, 0x48, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x22, 0x3e, 0x0a, 0x0a, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x46,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0c, 0x53, 0x65, 0x65, 0x6b, 0x69, 0x6e,
	0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x27, 0x0a, 0x08,
	0x53, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53,
	0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x6e, 0x6b, 0x6f, 0x62, 0x67, 0x2f, 0x6a, 0x75,
	0x69, 0x63, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_juicer_juicer_proto_rawDescOnce sync.Once
	file_proto_juicer_juicer_proto_rawDescData = file_proto_juicer_juicer_proto_rawDesc
)

func file_proto_juicer_juicer_proto_rawDescGZIP() []byte {
	file_proto_juicer_juicer_proto_rawDescOnce.Do(func() {
		file_proto_juicer_juicer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_juicer_juicer_proto_rawDescData)
	})
	return file_proto_juicer_juicer_proto_rawDescData
}

var file_proto_juicer_juicer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_juicer_juicer_proto_goTypes = []any{
	(*Message)(nil),            // 0: pb.Message
	(*Error)(nil),              // 1: pb.Error
	(*Echo)(nil),               // 2: pb.Echo
	(*ClientConnected)(nil),    // 3: pb.ClientConnected
	(*ClientDisconnected)(nil), // 4: pb.ClientDisconnected
	(*HubInfo)(nil),            // 5: pb.HubInfo
	(*MatchFound)(nil),         // 6: pb.MatchFound
	(*SeekingCount)(nil),       // 7: pb.SeekingCount
	(*SeekGame)(nil),           // 8: pb.SeekGame
	(*CancelSeekGame)(nil),     // 9: pb.CancelSeekGame
}
var file_proto_juicer_juicer_proto_depIdxs = []int32{
	1, // 0: pb.Message.error:type_name -> pb.Error
	2, // 1: pb.Message.echo:type_name -> pb.Echo
	3, // 2: pb.Message.client_connected:type_name -> pb.ClientConnected
	4, // 3: pb.Message.client_disconnected:type_name -> pb.ClientDisconnected
	5, // 4: pb.Message.hub_info:type_name -> pb.HubInfo
	6, // 5: pb.Message.match_found:type_name -> pb.MatchFound
	7, // 6: pb.Message.seeking_count:type_name -> pb.SeekingCount
	8, // 7: pb.Message.seek_game:type_name -> pb.SeekGame
	9, // 8: pb.Message.cancel_seek_game:type_name -> pb.CancelSeekGame
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_juicer_juicer_proto_init() }
func file_proto_juicer_juicer_proto_init() {
	if File_proto_juicer_juicer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_juicer_juicer_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ClientConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ClientDisconnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*HubInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MatchFound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SeekingCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SeekGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CancelSeekGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_juicer_juicer_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Error)(nil),
		(*Message_Echo)(nil),
		(*Message_ClientConnected)(nil),
		(*Message_ClientDisconnected)(nil),
		(*Message_HubInfo)(nil),
		(*Message_MatchFound)(nil),
		(*Message_SeekingCount)(nil),
		(*Message_SeekGame)(nil),
		(*Message_CancelSeekGame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_juicer_juicer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_juicer_juicer_proto_goTypes,
		DependencyIndexes: file_proto_juicer_juicer_proto_depIdxs,
		MessageInfos:      file_proto_juicer_juicer_proto_msgTypes,
	}.Build()
	File_proto_juicer_juicer_proto = out.File
	file_proto_juicer_juicer_proto_rawDesc = nil
	file_proto_juicer_juicer_proto_goTypes = nil
	file_proto_juicer_juicer_proto_depIdxs = nil
}
