// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: proto/juicer/juicer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*Message_Error
	//	*Message_Echo
	//	*Message_ClientConnected
	//	*Message_ClientDisconnected
	//	*Message_HubInfo
	//	*Message_MatchFound
	//	*Message_MatchRejoined
	//	*Message_SeekingCount
	//	*Message_SeekGame
	//	*Message_CancelSeekGame
	//	*Message_GameFinished
	//	*Message_AbortGame
	//	*Message_OfferDraw
	//	*Message_AcceptDraw
	//	*Message_PlayMoveUci
	//	*Message_Chat
	//	*Message_Move
	Event isMessage_Event `protobuf_oneof:"event"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetEvent() isMessage_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *Message) GetError() *Error {
	if x, ok := x.GetEvent().(*Message_Error); ok {
		return x.Error
	}
	return nil
}

func (x *Message) GetEcho() *Echo {
	if x, ok := x.GetEvent().(*Message_Echo); ok {
		return x.Echo
	}
	return nil
}

func (x *Message) GetClientConnected() *ClientConnected {
	if x, ok := x.GetEvent().(*Message_ClientConnected); ok {
		return x.ClientConnected
	}
	return nil
}

func (x *Message) GetClientDisconnected() *ClientDisconnected {
	if x, ok := x.GetEvent().(*Message_ClientDisconnected); ok {
		return x.ClientDisconnected
	}
	return nil
}

func (x *Message) GetHubInfo() *HubInfo {
	if x, ok := x.GetEvent().(*Message_HubInfo); ok {
		return x.HubInfo
	}
	return nil
}

func (x *Message) GetMatchFound() *MatchFound {
	if x, ok := x.GetEvent().(*Message_MatchFound); ok {
		return x.MatchFound
	}
	return nil
}

func (x *Message) GetMatchRejoined() *MatchRejoined {
	if x, ok := x.GetEvent().(*Message_MatchRejoined); ok {
		return x.MatchRejoined
	}
	return nil
}

func (x *Message) GetSeekingCount() *SeekingCount {
	if x, ok := x.GetEvent().(*Message_SeekingCount); ok {
		return x.SeekingCount
	}
	return nil
}

func (x *Message) GetSeekGame() *SeekGame {
	if x, ok := x.GetEvent().(*Message_SeekGame); ok {
		return x.SeekGame
	}
	return nil
}

func (x *Message) GetCancelSeekGame() *CancelSeekGame {
	if x, ok := x.GetEvent().(*Message_CancelSeekGame); ok {
		return x.CancelSeekGame
	}
	return nil
}

func (x *Message) GetGameFinished() *GameFinished {
	if x, ok := x.GetEvent().(*Message_GameFinished); ok {
		return x.GameFinished
	}
	return nil
}

func (x *Message) GetAbortGame() *AbortGame {
	if x, ok := x.GetEvent().(*Message_AbortGame); ok {
		return x.AbortGame
	}
	return nil
}

func (x *Message) GetOfferDraw() *OfferDraw {
	if x, ok := x.GetEvent().(*Message_OfferDraw); ok {
		return x.OfferDraw
	}
	return nil
}

func (x *Message) GetAcceptDraw() *AcceptDraw {
	if x, ok := x.GetEvent().(*Message_AcceptDraw); ok {
		return x.AcceptDraw
	}
	return nil
}

func (x *Message) GetPlayMoveUci() *PlayMoveUCI {
	if x, ok := x.GetEvent().(*Message_PlayMoveUci); ok {
		return x.PlayMoveUci
	}
	return nil
}

func (x *Message) GetChat() *Chat {
	if x, ok := x.GetEvent().(*Message_Chat); ok {
		return x.Chat
	}
	return nil
}

func (x *Message) GetMove() *Move {
	if x, ok := x.GetEvent().(*Message_Move); ok {
		return x.Move
	}
	return nil
}

type isMessage_Event interface {
	isMessage_Event()
}

type Message_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type Message_Echo struct {
	Echo *Echo `protobuf:"bytes,2,opt,name=echo,proto3,oneof"`
}

type Message_ClientConnected struct {
	ClientConnected *ClientConnected `protobuf:"bytes,3,opt,name=client_connected,json=clientConnected,proto3,oneof"`
}

type Message_ClientDisconnected struct {
	ClientDisconnected *ClientDisconnected `protobuf:"bytes,4,opt,name=client_disconnected,json=clientDisconnected,proto3,oneof"`
}

type Message_HubInfo struct {
	HubInfo *HubInfo `protobuf:"bytes,5,opt,name=hub_info,json=hubInfo,proto3,oneof"`
}

type Message_MatchFound struct {
	MatchFound *MatchFound `protobuf:"bytes,6,opt,name=match_found,json=matchFound,proto3,oneof"`
}

type Message_MatchRejoined struct {
	MatchRejoined *MatchRejoined `protobuf:"bytes,7,opt,name=match_rejoined,json=matchRejoined,proto3,oneof"`
}

type Message_SeekingCount struct {
	SeekingCount *SeekingCount `protobuf:"bytes,8,opt,name=seeking_count,json=seekingCount,proto3,oneof"`
}

type Message_SeekGame struct {
	SeekGame *SeekGame `protobuf:"bytes,9,opt,name=seek_game,json=seekGame,proto3,oneof"`
}

type Message_CancelSeekGame struct {
	CancelSeekGame *CancelSeekGame `protobuf:"bytes,10,opt,name=cancel_seek_game,json=cancelSeekGame,proto3,oneof"`
}

type Message_GameFinished struct {
	GameFinished *GameFinished `protobuf:"bytes,11,opt,name=game_finished,json=gameFinished,proto3,oneof"`
}

type Message_AbortGame struct {
	AbortGame *AbortGame `protobuf:"bytes,12,opt,name=abort_game,json=abortGame,proto3,oneof"`
}

type Message_OfferDraw struct {
	OfferDraw *OfferDraw `protobuf:"bytes,13,opt,name=offer_draw,json=offerDraw,proto3,oneof"`
}

type Message_AcceptDraw struct {
	AcceptDraw *AcceptDraw `protobuf:"bytes,14,opt,name=accept_draw,json=acceptDraw,proto3,oneof"`
}

type Message_PlayMoveUci struct {
	PlayMoveUci *PlayMoveUCI `protobuf:"bytes,15,opt,name=play_move_uci,json=playMoveUci,proto3,oneof"`
}

type Message_Chat struct {
	Chat *Chat `protobuf:"bytes,16,opt,name=chat,proto3,oneof"`
}

type Message_Move struct {
	Move *Move `protobuf:"bytes,17,opt,name=move,proto3,oneof"`
}

func (*Message_Error) isMessage_Event() {}

func (*Message_Echo) isMessage_Event() {}

func (*Message_ClientConnected) isMessage_Event() {}

func (*Message_ClientDisconnected) isMessage_Event() {}

func (*Message_HubInfo) isMessage_Event() {}

func (*Message_MatchFound) isMessage_Event() {}

func (*Message_MatchRejoined) isMessage_Event() {}

func (*Message_SeekingCount) isMessage_Event() {}

func (*Message_SeekGame) isMessage_Event() {}

func (*Message_CancelSeekGame) isMessage_Event() {}

func (*Message_GameFinished) isMessage_Event() {}

func (*Message_AbortGame) isMessage_Event() {}

func (*Message_OfferDraw) isMessage_Event() {}

func (*Message_AcceptDraw) isMessage_Event() {}

func (*Message_PlayMoveUci) isMessage_Event() {}

func (*Message_Chat) isMessage_Event() {}

func (*Message_Move) isMessage_Event() {}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{2}
}

func (x *Echo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientConnected) Reset() {
	*x = ClientConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnected) ProtoMessage() {}

func (x *ClientConnected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnected.ProtoReflect.Descriptor instead.
func (*ClientConnected) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{3}
}

func (x *ClientConnected) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClientDisconnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientDisconnected) Reset() {
	*x = ClientDisconnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnected) ProtoMessage() {}

func (x *ClientDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnected.ProtoReflect.Descriptor instead.
func (*ClientDisconnected) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{4}
}

func (x *ClientDisconnected) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HubInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lobby   int32 `protobuf:"varint,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	Rooms   int32 `protobuf:"varint,2,opt,name=rooms,proto3" json:"rooms,omitempty"`
	Playing int32 `protobuf:"varint,3,opt,name=playing,proto3" json:"playing,omitempty"`
}

func (x *HubInfo) Reset() {
	*x = HubInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubInfo) ProtoMessage() {}

func (x *HubInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubInfo.ProtoReflect.Descriptor instead.
func (*HubInfo) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{5}
}

func (x *HubInfo) GetLobby() int32 {
	if x != nil {
		return x.Lobby
	}
	return 0
}

func (x *HubInfo) GetRooms() int32 {
	if x != nil {
		return x.Rooms
	}
	return 0
}

func (x *HubInfo) GetPlaying() int32 {
	if x != nil {
		return x.Playing
	}
	return 0
}

type MatchFound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId     string   `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	RoomId     string   `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Color      string   `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Fen        string   `protobuf:"bytes,4,opt,name=fen,proto3" json:"fen,omitempty"`
	Ply        uint32   `protobuf:"varint,5,opt,name=ply,proto3" json:"ply,omitempty"`
	Clocks     *Clocks  `protobuf:"bytes,6,opt,name=clocks,proto3" json:"clocks,omitempty"`
	LegalMoves []string `protobuf:"bytes,7,rep,name=legal_moves,json=legalMoves,proto3" json:"legal_moves,omitempty"`
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{6}
}

func (x *MatchFound) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MatchFound) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchFound) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *MatchFound) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *MatchFound) GetPly() uint32 {
	if x != nil {
		return x.Ply
	}
	return 0
}

func (x *MatchFound) GetClocks() *Clocks {
	if x != nil {
		return x.Clocks
	}
	return nil
}

func (x *MatchFound) GetLegalMoves() []string {
	if x != nil {
		return x.LegalMoves
	}
	return nil
}

type MatchRejoined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId     string   `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	RoomId     string   `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Color      string   `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Fen        string   `protobuf:"bytes,4,opt,name=fen,proto3" json:"fen,omitempty"`
	Ply        uint32   `protobuf:"varint,5,opt,name=ply,proto3" json:"ply,omitempty"`
	Clocks     *Clocks  `protobuf:"bytes,6,opt,name=clocks,proto3" json:"clocks,omitempty"`
	LegalMoves []string `protobuf:"bytes,7,rep,name=legal_moves,json=legalMoves,proto3" json:"legal_moves,omitempty"`
}

func (x *MatchRejoined) Reset() {
	*x = MatchRejoined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRejoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRejoined) ProtoMessage() {}

func (x *MatchRejoined) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRejoined.ProtoReflect.Descriptor instead.
func (*MatchRejoined) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{7}
}

func (x *MatchRejoined) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MatchRejoined) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchRejoined) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *MatchRejoined) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *MatchRejoined) GetPly() uint32 {
	if x != nil {
		return x.Ply
	}
	return 0
}

func (x *MatchRejoined) GetClocks() *Clocks {
	if x != nil {
		return x.Clocks
	}
	return nil
}

func (x *MatchRejoined) GetLegalMoves() []string {
	if x != nil {
		return x.LegalMoves
	}
	return nil
}

type SeekingCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SeekingCount) Reset() {
	*x = SeekingCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekingCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekingCount) ProtoMessage() {}

func (x *SeekingCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekingCount.ProtoReflect.Descriptor instead.
func (*SeekingCount) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{8}
}

func (x *SeekingCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SeekGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameMode string `protobuf:"bytes,1,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
}

func (x *SeekGame) Reset() {
	*x = SeekGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekGame) ProtoMessage() {}

func (x *SeekGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekGame.ProtoReflect.Descriptor instead.
func (*SeekGame) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{9}
}

func (x *SeekGame) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

type CancelSeekGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelSeekGame) Reset() {
	*x = CancelSeekGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSeekGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSeekGame) ProtoMessage() {}

func (x *CancelSeekGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSeekGame.ProtoReflect.Descriptor instead.
func (*CancelSeekGame) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{10}
}

type GameFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GameFinished) Reset() {
	*x = GameFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFinished) ProtoMessage() {}

func (x *GameFinished) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFinished.ProtoReflect.Descriptor instead.
func (*GameFinished) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{11}
}

func (x *GameFinished) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameFinished) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameFinished) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GameFinished) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AbortGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbortGame) Reset() {
	*x = AbortGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortGame) ProtoMessage() {}

func (x *AbortGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortGame.ProtoReflect.Descriptor instead.
func (*AbortGame) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{12}
}

type OfferDraw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OfferDraw) Reset() {
	*x = OfferDraw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferDraw) ProtoMessage() {}

func (x *OfferDraw) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferDraw.ProtoReflect.Descriptor instead.
func (*OfferDraw) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{13}
}

type AcceptDraw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcceptDraw) Reset() {
	*x = AcceptDraw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptDraw) ProtoMessage() {}

func (x *AcceptDraw) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptDraw.ProtoReflect.Descriptor instead.
func (*AcceptDraw) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{14}
}

type PlayMoveUCI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Move string `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
}

func (x *PlayMoveUCI) Reset() {
	*x = PlayMoveUCI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayMoveUCI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoveUCI) ProtoMessage() {}

func (x *PlayMoveUCI) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoveUCI.ProtoReflect.Descriptor instead.
func (*PlayMoveUCI) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{15}
}

func (x *PlayMoveUCI) GetMove() string {
	if x != nil {
		return x.Move
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Chat) Reset() {
	*x = Chat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{16}
}

func (x *Chat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Clocks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	White float64 `protobuf:"fixed64,1,opt,name=white,proto3" json:"white,omitempty"`
	Black float64 `protobuf:"fixed64,2,opt,name=black,proto3" json:"black,omitempty"`
}

func (x *Clocks) Reset() {
	*x = Clocks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clocks) ProtoMessage() {}

func (x *Clocks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clocks.ProtoReflect.Descriptor instead.
func (*Clocks) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{17}
}

func (x *Clocks) GetWhite() float64 {
	if x != nil {
		return x.White
	}
	return 0
}

func (x *Clocks) GetBlack() float64 {
	if x != nil {
		return x.Black
	}
	return 0
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uci        string   `protobuf:"bytes,1,opt,name=uci,proto3" json:"uci,omitempty"`
	San        string   `protobuf:"bytes,2,opt,name=san,proto3" json:"san,omitempty"`
	Lan        string   `protobuf:"bytes,3,opt,name=lan,proto3" json:"lan,omitempty"`
	Fen        string   `protobuf:"bytes,4,opt,name=fen,proto3" json:"fen,omitempty"`
	Ply        uint32   `protobuf:"varint,5,opt,name=ply,proto3" json:"ply,omitempty"`
	Clocks     *Clocks  `protobuf:"bytes,6,opt,name=clocks,proto3" json:"clocks,omitempty"`
	LegalMoves []string `protobuf:"bytes,7,rep,name=legal_moves,json=legalMoves,proto3" json:"legal_moves,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_juicer_juicer_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{18}
}

func (x *Move) GetUci() string {
	if x != nil {
		return x.Uci
	}
	return ""
}

func (x *Move) GetSan() string {
	if x != nil {
		return x.San
	}
	return ""
}

func (x *Move) GetLan() string {
	if x != nil {
		return x.Lan
	}
	return ""
}

func (x *Move) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *Move) GetPly() uint32 {
	if x != nil {
		return x.Ply
	}
	return 0
}

func (x *Move) GetClocks() *Clocks {
	if x != nil {
		return x.Clocks
	}
	return nil
}

func (x *Move) GetLegalMoves() []string {
	if x != nil {
		return x.LegalMoves
	}
	return nil
}

var File_proto_juicer_juicer_proto protoreflect.FileDescriptor

var file_proto_juicer_juicer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x75, 0x69, 0x63, 0x65, 0x72, 0x2f, 0x6a,
	0x75, 0x69, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0xe4, 0x06, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1e,
	0x0a, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x12, 0x40,
	0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x12, 0x49, 0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x08, 0x68,
	0x75, 0x62, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x48, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x07, 0x68, 0x75,
	0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x3a, 0x0a, 0x0e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x72, 0x65, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6a, 0x6f, 0x69,
	0x6e, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6a, 0x6f,
	0x69, 0x6e, 0x65, 0x64, 0x12, 0x37, 0x0a, 0x0d, 0x73, 0x65, 0x65, 0x6b, 0x69, 0x6e, 0x67, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x65, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x0c, 0x73, 0x65, 0x65, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x0a,
	0x09, 0x73, 0x65, 0x65, 0x6b, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00,
	0x52, 0x08, 0x73, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x10, 0x63, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x73, 0x65, 0x65, 0x6b, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x53, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x53, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x0a, 0x61, 0x62, 0x6f, 0x72, 0x74, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x62, 0x6f,
	0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x09, 0x61, 0x62, 0x6f, 0x72, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x64, 0x72, 0x61,
	0x77, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x44, 0x72, 0x61, 0x77, 0x48, 0x00, 0x52, 0x09, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x44,
	0x72, 0x61, 0x77, 0x12, 0x31, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x5f, 0x64, 0x72,
	0x61, 0x77, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x44, 0x72, 0x61, 0x77, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x44, 0x72, 0x61, 0x77, 0x12, 0x35, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6d,
	0x6f, 0x76, 0x65, 0x5f, 0x75, 0x63, 0x69, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x4d, 0x6f, 0x76, 0x65, 0x55, 0x43, 0x49, 0x48, 0x00,
	0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x6f, 0x76, 0x65, 0x55, 0x63, 0x69, 0x12, 0x1e, 0x0a,
	0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x48, 0x00, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x12, 0x1e, 0x0a,
	0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x07, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x04, 0x45, 0x63, 0x68,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24,
	0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x4f, 0x0a, 0x07, 0x48, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x69, 0x6e, 0x67, 0x22, 0xbd, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x46,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x66, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x6c, 0x79,
	0x12, 0x22, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x06, 0x63, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x67, 0x61, 0x6c, 0x5f, 0x6d, 0x6f,
	0x76, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x67, 0x61, 0x6c,
	0x4d, 0x6f, 0x76, 0x65, 0x73, 0x22, 0xc0, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x65,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52,
	0x06, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x67, 0x61, 0x6c,
	0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65,
	0x67, 0x61, 0x6c, 0x4d, 0x6f, 0x76, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x0c, 0x53, 0x65, 0x65, 0x6b,
	0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x27,
	0x0a, 0x08, 0x53, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67,
	0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x53, 0x65, 0x65, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x70, 0x0a, 0x0c, 0x47, 0x61, 0x6d,
	0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x0b, 0x0a, 0x09, 0x41,
	0x62, 0x6f, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x44, 0x72, 0x61, 0x77, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x44,
	0x72, 0x61, 0x77, 0x22, 0x21, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x4d, 0x6f, 0x76, 0x65, 0x55,
	0x43, 0x49, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x20, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x43, 0x6c, 0x6f, 0x63,
	0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x61, 0x63,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x22, 0xa5,
	0x01, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x63, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x63, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x61, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x61, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x66, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x6c,
	0x79, 0x12, 0x22, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x06, 0x63,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x67, 0x61, 0x6c, 0x5f, 0x6d,
	0x6f, 0x76, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x67, 0x61,
	0x6c, 0x4d, 0x6f, 0x76, 0x65, 0x73, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x6e, 0x6b, 0x6f, 0x62, 0x67, 0x2f, 0x6a, 0x75, 0x69,
	0x63, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_juicer_juicer_proto_rawDescOnce sync.Once
	file_proto_juicer_juicer_proto_rawDescData = file_proto_juicer_juicer_proto_rawDesc
)

func file_proto_juicer_juicer_proto_rawDescGZIP() []byte {
	file_proto_juicer_juicer_proto_rawDescOnce.Do(func() {
		file_proto_juicer_juicer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_juicer_juicer_proto_rawDescData)
	})
	return file_proto_juicer_juicer_proto_rawDescData
}

var file_proto_juicer_juicer_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_juicer_juicer_proto_goTypes = []any{
	(*Message)(nil),            // 0: pb.Message
	(*Error)(nil),              // 1: pb.Error
	(*Echo)(nil),               // 2: pb.Echo
	(*ClientConnected)(nil),    // 3: pb.ClientConnected
	(*ClientDisconnected)(nil), // 4: pb.ClientDisconnected
	(*HubInfo)(nil),            // 5: pb.HubInfo
	(*MatchFound)(nil),         // 6: pb.MatchFound
	(*MatchRejoined)(nil),      // 7: pb.MatchRejoined
	(*SeekingCount)(nil),       // 8: pb.SeekingCount
	(*SeekGame)(nil),           // 9: pb.SeekGame
	(*CancelSeekGame)(nil),     // 10: pb.CancelSeekGame
	(*GameFinished)(nil),       // 11: pb.GameFinished
	(*AbortGame)(nil),          // 12: pb.AbortGame
	(*OfferDraw)(nil),          // 13: pb.OfferDraw
	(*AcceptDraw)(nil),         // 14: pb.AcceptDraw
	(*PlayMoveUCI)(nil),        // 15: pb.PlayMoveUCI
	(*Chat)(nil),               // 16: pb.Chat
	(*Clocks)(nil),             // 17: pb.Clocks
	(*Move)(nil),               // 18: pb.Move
}
var file_proto_juicer_juicer_proto_depIdxs = []int32{
	1,  // 0: pb.Message.error:type_name -> pb.Error
	2,  // 1: pb.Message.echo:type_name -> pb.Echo
	3,  // 2: pb.Message.client_connected:type_name -> pb.ClientConnected
	4,  // 3: pb.Message.client_disconnected:type_name -> pb.ClientDisconnected
	5,  // 4: pb.Message.hub_info:type_name -> pb.HubInfo
	6,  // 5: pb.Message.match_found:type_name -> pb.MatchFound
	7,  // 6: pb.Message.match_rejoined:type_name -> pb.MatchRejoined
	8,  // 7: pb.Message.seeking_count:type_name -> pb.SeekingCount
	9,  // 8: pb.Message.seek_game:type_name -> pb.SeekGame
	10, // 9: pb.Message.cancel_seek_game:type_name -> pb.CancelSeekGame
	11, // 10: pb.Message.game_finished:type_name -> pb.GameFinished
	12, // 11: pb.Message.abort_game:type_name -> pb.AbortGame
	13, // 12: pb.Message.offer_draw:type_name -> pb.OfferDraw
	14, // 13: pb.Message.accept_draw:type_name -> pb.AcceptDraw
	15, // 14: pb.Message.play_move_uci:type_name -> pb.PlayMoveUCI
	16, // 15: pb.Message.chat:type_name -> pb.Chat
	18, // 16: pb.Message.move:type_name -> pb.Move
	17, // 17: pb.MatchFound.clocks:type_name -> pb.Clocks
	17, // 18: pb.MatchRejoined.clocks:type_name -> pb.Clocks
	17, // 19: pb.Move.clocks:type_name -> pb.Clocks
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_juicer_juicer_proto_init() }
func file_proto_juicer_juicer_proto_init() {
	if File_proto_juicer_juicer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_juicer_juicer_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ClientConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ClientDisconnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*HubInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MatchFound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*MatchRejoined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SeekingCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SeekGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CancelSeekGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GameFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AbortGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*OfferDraw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*AcceptDraw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*PlayMoveUCI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*Chat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*Clocks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_juicer_juicer_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_juicer_juicer_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Error)(nil),
		(*Message_Echo)(nil),
		(*Message_ClientConnected)(nil),
		(*Message_ClientDisconnected)(nil),
		(*Message_HubInfo)(nil),
		(*Message_MatchFound)(nil),
		(*Message_MatchRejoined)(nil),
		(*Message_SeekingCount)(nil),
		(*Message_SeekGame)(nil),
		(*Message_CancelSeekGame)(nil),
		(*Message_GameFinished)(nil),
		(*Message_AbortGame)(nil),
		(*Message_OfferDraw)(nil),
		(*Message_AcceptDraw)(nil),
		(*Message_PlayMoveUci)(nil),
		(*Message_Chat)(nil),
		(*Message_Move)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_juicer_juicer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_juicer_juicer_proto_goTypes,
		DependencyIndexes: file_proto_juicer_juicer_proto_depIdxs,
		MessageInfos:      file_proto_juicer_juicer_proto_msgTypes,
	}.Build()
	File_proto_juicer_juicer_proto = out.File
	file_proto_juicer_juicer_proto_rawDesc = nil
	file_proto_juicer_juicer_proto_goTypes = nil
	file_proto_juicer_juicer_proto_depIdxs = nil
}
