// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/juicer/juicer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Color is the player color
type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_WHITE       Color = 1
	Color_COLOR_BLACK       Color = 2
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "COLOR_WHITE",
		2: "COLOR_BLACK",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_WHITE":       1,
		"COLOR_BLACK":       2,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_juicer_juicer_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_proto_juicer_juicer_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{0}
}

// GameVariant is game variant
type GameVariant int32

const (
	GameVariant_GAME_VARIANT_UNSPECIFIED      GameVariant = 0
	GameVariant_GAME_VARIANT_STANDARD         GameVariant = 1
	GameVariant_GAME_VARIANT_ATOMIC           GameVariant = 2
	GameVariant_GAME_VARIANT_CRAZYHOUSE       GameVariant = 3
	GameVariant_GAME_VARIANT_CHESS960         GameVariant = 4
	GameVariant_GAME_VARIANT_KING_OF_THE_HILL GameVariant = 5
	GameVariant_GAME_VARIANT_THREE_CHECK      GameVariant = 6
	GameVariant_GAME_VARIANT_HORDE            GameVariant = 7
	GameVariant_GAME_VARIANT_RACING_KINGS     GameVariant = 8
)

// Enum value maps for GameVariant.
var (
	GameVariant_name = map[int32]string{
		0: "GAME_VARIANT_UNSPECIFIED",
		1: "GAME_VARIANT_STANDARD",
		2: "GAME_VARIANT_ATOMIC",
		3: "GAME_VARIANT_CRAZYHOUSE",
		4: "GAME_VARIANT_CHESS960",
		5: "GAME_VARIANT_KING_OF_THE_HILL",
		6: "GAME_VARIANT_THREE_CHECK",
		7: "GAME_VARIANT_HORDE",
		8: "GAME_VARIANT_RACING_KINGS",
	}
	GameVariant_value = map[string]int32{
		"GAME_VARIANT_UNSPECIFIED":      0,
		"GAME_VARIANT_STANDARD":         1,
		"GAME_VARIANT_ATOMIC":           2,
		"GAME_VARIANT_CRAZYHOUSE":       3,
		"GAME_VARIANT_CHESS960":         4,
		"GAME_VARIANT_KING_OF_THE_HILL": 5,
		"GAME_VARIANT_THREE_CHECK":      6,
		"GAME_VARIANT_HORDE":            7,
		"GAME_VARIANT_RACING_KINGS":     8,
	}
)

func (x GameVariant) Enum() *GameVariant {
	p := new(GameVariant)
	*p = x
	return p
}

func (x GameVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_juicer_juicer_proto_enumTypes[1].Descriptor()
}

func (GameVariant) Type() protoreflect.EnumType {
	return &file_proto_juicer_juicer_proto_enumTypes[1]
}

func (x GameVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameVariant.Descriptor instead.
func (GameVariant) EnumDescriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{1}
}

// GameTimeKind is game time kind
type GameTimeKind int32

const (
	GameTimeKind_GAME_TIME_KIND_UNSPECIFIED    GameTimeKind = 0
	GameTimeKind_GAME_TIME_KIND_REALTIME       GameTimeKind = 1
	GameTimeKind_GAME_TIME_KIND_CORRESPONDENCE GameTimeKind = 2
	GameTimeKind_GAME_TIME_KIND_UNLIMITED      GameTimeKind = 3
)

// Enum value maps for GameTimeKind.
var (
	GameTimeKind_name = map[int32]string{
		0: "GAME_TIME_KIND_UNSPECIFIED",
		1: "GAME_TIME_KIND_REALTIME",
		2: "GAME_TIME_KIND_CORRESPONDENCE",
		3: "GAME_TIME_KIND_UNLIMITED",
	}
	GameTimeKind_value = map[string]int32{
		"GAME_TIME_KIND_UNSPECIFIED":    0,
		"GAME_TIME_KIND_REALTIME":       1,
		"GAME_TIME_KIND_CORRESPONDENCE": 2,
		"GAME_TIME_KIND_UNLIMITED":      3,
	}
)

func (x GameTimeKind) Enum() *GameTimeKind {
	p := new(GameTimeKind)
	*p = x
	return p
}

func (x GameTimeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameTimeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_juicer_juicer_proto_enumTypes[2].Descriptor()
}

func (GameTimeKind) Type() protoreflect.EnumType {
	return &file_proto_juicer_juicer_proto_enumTypes[2]
}

func (x GameTimeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameTimeKind.Descriptor instead.
func (GameTimeKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{2}
}

// GameTimeCategory is game time category
type GameTimeCategory int32

const (
	GameTimeCategory_GAME_TIME_CATEGORY_UNSPECIFIED GameTimeCategory = 0
	GameTimeCategory_GAME_TIME_CATEGORY_HYPERBULLET GameTimeCategory = 1
	GameTimeCategory_GAME_TIME_CATEGORY_BULLET      GameTimeCategory = 2
	GameTimeCategory_GAME_TIME_CATEGORY_BLITZ       GameTimeCategory = 3
	GameTimeCategory_GAME_TIME_CATEGORY_RAPID       GameTimeCategory = 4
	GameTimeCategory_GAME_TIME_CATEGORY_CLASSICAL   GameTimeCategory = 5
)

// Enum value maps for GameTimeCategory.
var (
	GameTimeCategory_name = map[int32]string{
		0: "GAME_TIME_CATEGORY_UNSPECIFIED",
		1: "GAME_TIME_CATEGORY_HYPERBULLET",
		2: "GAME_TIME_CATEGORY_BULLET",
		3: "GAME_TIME_CATEGORY_BLITZ",
		4: "GAME_TIME_CATEGORY_RAPID",
		5: "GAME_TIME_CATEGORY_CLASSICAL",
	}
	GameTimeCategory_value = map[string]int32{
		"GAME_TIME_CATEGORY_UNSPECIFIED": 0,
		"GAME_TIME_CATEGORY_HYPERBULLET": 1,
		"GAME_TIME_CATEGORY_BULLET":      2,
		"GAME_TIME_CATEGORY_BLITZ":       3,
		"GAME_TIME_CATEGORY_RAPID":       4,
		"GAME_TIME_CATEGORY_CLASSICAL":   5,
	}
)

func (x GameTimeCategory) Enum() *GameTimeCategory {
	p := new(GameTimeCategory)
	*p = x
	return p
}

func (x GameTimeCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameTimeCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_juicer_juicer_proto_enumTypes[3].Descriptor()
}

func (GameTimeCategory) Type() protoreflect.EnumType {
	return &file_proto_juicer_juicer_proto_enumTypes[3]
}

func (x GameTimeCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameTimeCategory.Descriptor instead.
func (GameTimeCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{3}
}

// GameResult is result of the game
type GameResult int32

const (
	GameResult_GAME_RESULT_UNSPECIFIED GameResult = 0
	GameResult_GAME_RESULT_WHITE_WON   GameResult = 1
	GameResult_GAME_RESULT_BLACK_WON   GameResult = 2
	GameResult_GAME_RESULT_DRAW        GameResult = 3
	GameResult_GAME_RESULT_INTERRUPTED GameResult = 4
)

// Enum value maps for GameResult.
var (
	GameResult_name = map[int32]string{
		0: "GAME_RESULT_UNSPECIFIED",
		1: "GAME_RESULT_WHITE_WON",
		2: "GAME_RESULT_BLACK_WON",
		3: "GAME_RESULT_DRAW",
		4: "GAME_RESULT_INTERRUPTED",
	}
	GameResult_value = map[string]int32{
		"GAME_RESULT_UNSPECIFIED": 0,
		"GAME_RESULT_WHITE_WON":   1,
		"GAME_RESULT_BLACK_WON":   2,
		"GAME_RESULT_DRAW":        3,
		"GAME_RESULT_INTERRUPTED": 4,
	}
)

func (x GameResult) Enum() *GameResult {
	p := new(GameResult)
	*p = x
	return p
}

func (x GameResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_juicer_juicer_proto_enumTypes[4].Descriptor()
}

func (GameResult) Type() protoreflect.EnumType {
	return &file_proto_juicer_juicer_proto_enumTypes[4]
}

func (x GameResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameResult.Descriptor instead.
func (GameResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{4}
}

// GameResultStatus specifies the reason of result
type GameResultStatus int32

const (
	GameResultStatus_GAME_RESULT_STATUS_UNSPECIFIED           GameResultStatus = 0
	GameResultStatus_GAME_RESULT_STATUS_CHECKMATE             GameResultStatus = 1
	GameResultStatus_GAME_RESULT_STATUS_INSUFFICIENT_MATERIAL GameResultStatus = 2
	GameResultStatus_GAME_RESULT_STATUS_THREEFOLD_REPETITION  GameResultStatus = 3
	GameResultStatus_GAME_RESULT_STATUS_FIVEFOLD_REPETITION   GameResultStatus = 4
	GameResultStatus_GAME_RESULT_STATUS_FIFTY_MOVE_RULE       GameResultStatus = 5
	GameResultStatus_GAME_RESULT_STATUS_SEVENTYFIVE_MOVE_RULE GameResultStatus = 6
	GameResultStatus_GAME_RESULT_STATUS_STALEMATE             GameResultStatus = 7
	GameResultStatus_GAME_RESULT_STATUS_RESIGNATION           GameResultStatus = 8
	GameResultStatus_GAME_RESULT_STATUS_DRAW_AGREED           GameResultStatus = 9
	GameResultStatus_GAME_RESULT_STATUS_FLAGGED               GameResultStatus = 10
	GameResultStatus_GAME_RESULT_STATUS_ADJUDICATION          GameResultStatus = 11
	GameResultStatus_GAME_RESULT_STATUS_TIMED_OUT             GameResultStatus = 12
	GameResultStatus_GAME_RESULT_STATUS_ABORTED               GameResultStatus = 13
	GameResultStatus_GAME_RESULT_STATUS_INTERRUPTED           GameResultStatus = 14
)

// Enum value maps for GameResultStatus.
var (
	GameResultStatus_name = map[int32]string{
		0:  "GAME_RESULT_STATUS_UNSPECIFIED",
		1:  "GAME_RESULT_STATUS_CHECKMATE",
		2:  "GAME_RESULT_STATUS_INSUFFICIENT_MATERIAL",
		3:  "GAME_RESULT_STATUS_THREEFOLD_REPETITION",
		4:  "GAME_RESULT_STATUS_FIVEFOLD_REPETITION",
		5:  "GAME_RESULT_STATUS_FIFTY_MOVE_RULE",
		6:  "GAME_RESULT_STATUS_SEVENTYFIVE_MOVE_RULE",
		7:  "GAME_RESULT_STATUS_STALEMATE",
		8:  "GAME_RESULT_STATUS_RESIGNATION",
		9:  "GAME_RESULT_STATUS_DRAW_AGREED",
		10: "GAME_RESULT_STATUS_FLAGGED",
		11: "GAME_RESULT_STATUS_ADJUDICATION",
		12: "GAME_RESULT_STATUS_TIMED_OUT",
		13: "GAME_RESULT_STATUS_ABORTED",
		14: "GAME_RESULT_STATUS_INTERRUPTED",
	}
	GameResultStatus_value = map[string]int32{
		"GAME_RESULT_STATUS_UNSPECIFIED":           0,
		"GAME_RESULT_STATUS_CHECKMATE":             1,
		"GAME_RESULT_STATUS_INSUFFICIENT_MATERIAL": 2,
		"GAME_RESULT_STATUS_THREEFOLD_REPETITION":  3,
		"GAME_RESULT_STATUS_FIVEFOLD_REPETITION":   4,
		"GAME_RESULT_STATUS_FIFTY_MOVE_RULE":       5,
		"GAME_RESULT_STATUS_SEVENTYFIVE_MOVE_RULE": 6,
		"GAME_RESULT_STATUS_STALEMATE":             7,
		"GAME_RESULT_STATUS_RESIGNATION":           8,
		"GAME_RESULT_STATUS_DRAW_AGREED":           9,
		"GAME_RESULT_STATUS_FLAGGED":               10,
		"GAME_RESULT_STATUS_ADJUDICATION":          11,
		"GAME_RESULT_STATUS_TIMED_OUT":             12,
		"GAME_RESULT_STATUS_ABORTED":               13,
		"GAME_RESULT_STATUS_INTERRUPTED":           14,
	}
)

func (x GameResultStatus) Enum() *GameResultStatus {
	p := new(GameResultStatus)
	*p = x
	return p
}

func (x GameResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_juicer_juicer_proto_enumTypes[5].Descriptor()
}

func (GameResultStatus) Type() protoreflect.EnumType {
	return &file_proto_juicer_juicer_proto_enumTypes[5]
}

func (x GameResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameResultStatus.Descriptor instead.
func (GameResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{5}
}

// GameState is a game state
type GameState int32

const (
	GameState_GAME_STATE_UNSPECIFIED   GameState = 0
	GameState_GAME_STATE_IDLE          GameState = 1
	GameState_GAME_STATE_WAITING_START GameState = 2
	GameState_GAME_STATE_IN_PROGRESS   GameState = 3
	GameState_GAME_STATE_FINISHED      GameState = 4
	GameState_GAME_STATE_INTERRUPTED   GameState = 5
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0: "GAME_STATE_UNSPECIFIED",
		1: "GAME_STATE_IDLE",
		2: "GAME_STATE_WAITING_START",
		3: "GAME_STATE_IN_PROGRESS",
		4: "GAME_STATE_FINISHED",
		5: "GAME_STATE_INTERRUPTED",
	}
	GameState_value = map[string]int32{
		"GAME_STATE_UNSPECIFIED":   0,
		"GAME_STATE_IDLE":          1,
		"GAME_STATE_WAITING_START": 2,
		"GAME_STATE_IN_PROGRESS":   3,
		"GAME_STATE_FINISHED":      4,
		"GAME_STATE_INTERRUPTED":   5,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_juicer_juicer_proto_enumTypes[6].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_proto_juicer_juicer_proto_enumTypes[6]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{6}
}

// GameSideChoice is a choice when playing custom game
type GameSideChoice int32

const (
	GameSideChoice_GAME_SIDE_CHOICE_UNSPECIFIED GameSideChoice = 0
	GameSideChoice_GAME_SIDE_CHOICE_RANDOM      GameSideChoice = 1
	GameSideChoice_GAME_SIDE_CHOICE_WHITE       GameSideChoice = 2
	GameSideChoice_GAME_SIDE_CHOICE_BLACK       GameSideChoice = 3
)

// Enum value maps for GameSideChoice.
var (
	GameSideChoice_name = map[int32]string{
		0: "GAME_SIDE_CHOICE_UNSPECIFIED",
		1: "GAME_SIDE_CHOICE_RANDOM",
		2: "GAME_SIDE_CHOICE_WHITE",
		3: "GAME_SIDE_CHOICE_BLACK",
	}
	GameSideChoice_value = map[string]int32{
		"GAME_SIDE_CHOICE_UNSPECIFIED": 0,
		"GAME_SIDE_CHOICE_RANDOM":      1,
		"GAME_SIDE_CHOICE_WHITE":       2,
		"GAME_SIDE_CHOICE_BLACK":       3,
	}
)

func (x GameSideChoice) Enum() *GameSideChoice {
	p := new(GameSideChoice)
	*p = x
	return p
}

func (x GameSideChoice) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameSideChoice) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_juicer_juicer_proto_enumTypes[7].Descriptor()
}

func (GameSideChoice) Type() protoreflect.EnumType {
	return &file_proto_juicer_juicer_proto_enumTypes[7]
}

func (x GameSideChoice) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameSideChoice.Descriptor instead.
func (GameSideChoice) EnumDescriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{7}
}

// GameTimeControl is game time control
type GameTimeControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clock         *durationpb.Duration   `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Increment     *durationpb.Duration   `protobuf:"bytes,2,opt,name=increment,proto3" json:"increment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTimeControl) Reset() {
	*x = GameTimeControl{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTimeControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTimeControl) ProtoMessage() {}

func (x *GameTimeControl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTimeControl.ProtoReflect.Descriptor instead.
func (*GameTimeControl) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{0}
}

func (x *GameTimeControl) GetClock() *durationpb.Duration {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *GameTimeControl) GetIncrement() *durationpb.Duration {
	if x != nil {
		return x.Increment
	}
	return nil
}

// Message represents websocket message
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Message_Problem
	//	*Message_Latency
	//	*Message_Heartbeat
	//	*Message_LeaveTab
	//	*Message_LeaveSite
	//	*Message_ClientConnected
	//	*Message_ClientDisconnected
	//	*Message_RequestInitialChannels
	//	*Message_InitialChannels
	//	*Message_RequestChannelsInfo
	//	*Message_PresenceChanged
	//	*Message_SeekGame
	//	*Message_CancelSeekGame
	//	*Message_HubInfo
	//	*Message_MatchFound
	//	*Message_GameAbort
	//	*Message_GameResign
	//	*Message_GameOfferDraw
	//	*Message_GameAcceptDraw
	//	*Message_GameDeclineDraw
	//	*Message_GameChat
	//	*Message_GameChatReceive
	//	*Message_GameChatRetrieve
	//	*Message_PlayMoveUci
	//	*Message_ReceiveMove
	//	*Message_GameFinished
	//	*Message_Echo
	Event         isMessage_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetEvent() isMessage_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Message) GetProblem() *Problem {
	if x != nil {
		if x, ok := x.Event.(*Message_Problem); ok {
			return x.Problem
		}
	}
	return nil
}

func (x *Message) GetLatency() *Latency {
	if x != nil {
		if x, ok := x.Event.(*Message_Latency); ok {
			return x.Latency
		}
	}
	return nil
}

func (x *Message) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*Message_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Message) GetLeaveTab() *LeaveTab {
	if x != nil {
		if x, ok := x.Event.(*Message_LeaveTab); ok {
			return x.LeaveTab
		}
	}
	return nil
}

func (x *Message) GetLeaveSite() *LeaveSite {
	if x != nil {
		if x, ok := x.Event.(*Message_LeaveSite); ok {
			return x.LeaveSite
		}
	}
	return nil
}

func (x *Message) GetClientConnected() *ClientConnected {
	if x != nil {
		if x, ok := x.Event.(*Message_ClientConnected); ok {
			return x.ClientConnected
		}
	}
	return nil
}

func (x *Message) GetClientDisconnected() *ClientDisconnected {
	if x != nil {
		if x, ok := x.Event.(*Message_ClientDisconnected); ok {
			return x.ClientDisconnected
		}
	}
	return nil
}

func (x *Message) GetRequestInitialChannels() *RequestInitialChannels {
	if x != nil {
		if x, ok := x.Event.(*Message_RequestInitialChannels); ok {
			return x.RequestInitialChannels
		}
	}
	return nil
}

func (x *Message) GetInitialChannels() *InitialChannels {
	if x != nil {
		if x, ok := x.Event.(*Message_InitialChannels); ok {
			return x.InitialChannels
		}
	}
	return nil
}

func (x *Message) GetRequestChannelsInfo() *RequestChannelsInfo {
	if x != nil {
		if x, ok := x.Event.(*Message_RequestChannelsInfo); ok {
			return x.RequestChannelsInfo
		}
	}
	return nil
}

func (x *Message) GetPresenceChanged() *PresenceChanged {
	if x != nil {
		if x, ok := x.Event.(*Message_PresenceChanged); ok {
			return x.PresenceChanged
		}
	}
	return nil
}

func (x *Message) GetSeekGame() *SeekGame {
	if x != nil {
		if x, ok := x.Event.(*Message_SeekGame); ok {
			return x.SeekGame
		}
	}
	return nil
}

func (x *Message) GetCancelSeekGame() *CancelSeekGame {
	if x != nil {
		if x, ok := x.Event.(*Message_CancelSeekGame); ok {
			return x.CancelSeekGame
		}
	}
	return nil
}

func (x *Message) GetHubInfo() *HubInfo {
	if x != nil {
		if x, ok := x.Event.(*Message_HubInfo); ok {
			return x.HubInfo
		}
	}
	return nil
}

func (x *Message) GetMatchFound() *MatchFound {
	if x != nil {
		if x, ok := x.Event.(*Message_MatchFound); ok {
			return x.MatchFound
		}
	}
	return nil
}

func (x *Message) GetGameAbort() *GameAbort {
	if x != nil {
		if x, ok := x.Event.(*Message_GameAbort); ok {
			return x.GameAbort
		}
	}
	return nil
}

func (x *Message) GetGameResign() *GameResign {
	if x != nil {
		if x, ok := x.Event.(*Message_GameResign); ok {
			return x.GameResign
		}
	}
	return nil
}

func (x *Message) GetGameOfferDraw() *GameOfferDraw {
	if x != nil {
		if x, ok := x.Event.(*Message_GameOfferDraw); ok {
			return x.GameOfferDraw
		}
	}
	return nil
}

func (x *Message) GetGameAcceptDraw() *GameAcceptDraw {
	if x != nil {
		if x, ok := x.Event.(*Message_GameAcceptDraw); ok {
			return x.GameAcceptDraw
		}
	}
	return nil
}

func (x *Message) GetGameDeclineDraw() *GameDeclineDraw {
	if x != nil {
		if x, ok := x.Event.(*Message_GameDeclineDraw); ok {
			return x.GameDeclineDraw
		}
	}
	return nil
}

func (x *Message) GetGameChat() *GameChat {
	if x != nil {
		if x, ok := x.Event.(*Message_GameChat); ok {
			return x.GameChat
		}
	}
	return nil
}

func (x *Message) GetGameChatReceive() *GameChatReceive {
	if x != nil {
		if x, ok := x.Event.(*Message_GameChatReceive); ok {
			return x.GameChatReceive
		}
	}
	return nil
}

func (x *Message) GetGameChatRetrieve() *GameChatRetrieve {
	if x != nil {
		if x, ok := x.Event.(*Message_GameChatRetrieve); ok {
			return x.GameChatRetrieve
		}
	}
	return nil
}

func (x *Message) GetPlayMoveUci() *PlayMoveUCI {
	if x != nil {
		if x, ok := x.Event.(*Message_PlayMoveUci); ok {
			return x.PlayMoveUci
		}
	}
	return nil
}

func (x *Message) GetReceiveMove() *ReceiveMove {
	if x != nil {
		if x, ok := x.Event.(*Message_ReceiveMove); ok {
			return x.ReceiveMove
		}
	}
	return nil
}

func (x *Message) GetGameFinished() *GameFinished {
	if x != nil {
		if x, ok := x.Event.(*Message_GameFinished); ok {
			return x.GameFinished
		}
	}
	return nil
}

func (x *Message) GetEcho() *Echo {
	if x != nil {
		if x, ok := x.Event.(*Message_Echo); ok {
			return x.Echo
		}
	}
	return nil
}

type isMessage_Event interface {
	isMessage_Event()
}

type Message_Problem struct {
	Problem *Problem `protobuf:"bytes,1,opt,name=problem,proto3,oneof"`
}

type Message_Latency struct {
	Latency *Latency `protobuf:"bytes,2,opt,name=latency,proto3,oneof"`
}

type Message_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type Message_LeaveTab struct {
	LeaveTab *LeaveTab `protobuf:"bytes,4,opt,name=leave_tab,json=leaveTab,proto3,oneof"`
}

type Message_LeaveSite struct {
	LeaveSite *LeaveSite `protobuf:"bytes,5,opt,name=leave_site,json=leaveSite,proto3,oneof"`
}

type Message_ClientConnected struct {
	ClientConnected *ClientConnected `protobuf:"bytes,6,opt,name=client_connected,json=clientConnected,proto3,oneof"`
}

type Message_ClientDisconnected struct {
	ClientDisconnected *ClientDisconnected `protobuf:"bytes,7,opt,name=client_disconnected,json=clientDisconnected,proto3,oneof"`
}

type Message_RequestInitialChannels struct {
	RequestInitialChannels *RequestInitialChannels `protobuf:"bytes,8,opt,name=request_initial_channels,json=requestInitialChannels,proto3,oneof"`
}

type Message_InitialChannels struct {
	InitialChannels *InitialChannels `protobuf:"bytes,9,opt,name=initial_channels,json=initialChannels,proto3,oneof"`
}

type Message_RequestChannelsInfo struct {
	RequestChannelsInfo *RequestChannelsInfo `protobuf:"bytes,10,opt,name=request_channels_info,json=requestChannelsInfo,proto3,oneof"`
}

type Message_PresenceChanged struct {
	PresenceChanged *PresenceChanged `protobuf:"bytes,11,opt,name=presence_changed,json=presenceChanged,proto3,oneof"`
}

type Message_SeekGame struct {
	// ------------------------------------------------------
	SeekGame *SeekGame `protobuf:"bytes,12,opt,name=seek_game,json=seekGame,proto3,oneof"`
}

type Message_CancelSeekGame struct {
	CancelSeekGame *CancelSeekGame `protobuf:"bytes,13,opt,name=cancel_seek_game,json=cancelSeekGame,proto3,oneof"`
}

type Message_HubInfo struct {
	HubInfo *HubInfo `protobuf:"bytes,14,opt,name=hub_info,json=hubInfo,proto3,oneof"`
}

type Message_MatchFound struct {
	MatchFound *MatchFound `protobuf:"bytes,15,opt,name=match_found,json=matchFound,proto3,oneof"`
}

type Message_GameAbort struct {
	GameAbort *GameAbort `protobuf:"bytes,16,opt,name=game_abort,json=gameAbort,proto3,oneof"`
}

type Message_GameResign struct {
	GameResign *GameResign `protobuf:"bytes,17,opt,name=game_resign,json=gameResign,proto3,oneof"`
}

type Message_GameOfferDraw struct {
	GameOfferDraw *GameOfferDraw `protobuf:"bytes,18,opt,name=game_offer_draw,json=gameOfferDraw,proto3,oneof"`
}

type Message_GameAcceptDraw struct {
	GameAcceptDraw *GameAcceptDraw `protobuf:"bytes,19,opt,name=game_accept_draw,json=gameAcceptDraw,proto3,oneof"`
}

type Message_GameDeclineDraw struct {
	GameDeclineDraw *GameDeclineDraw `protobuf:"bytes,20,opt,name=game_decline_draw,json=gameDeclineDraw,proto3,oneof"`
}

type Message_GameChat struct {
	GameChat *GameChat `protobuf:"bytes,21,opt,name=game_chat,json=gameChat,proto3,oneof"`
}

type Message_GameChatReceive struct {
	GameChatReceive *GameChatReceive `protobuf:"bytes,22,opt,name=game_chat_receive,json=gameChatReceive,proto3,oneof"`
}

type Message_GameChatRetrieve struct {
	GameChatRetrieve *GameChatRetrieve `protobuf:"bytes,23,opt,name=game_chat_retrieve,json=gameChatRetrieve,proto3,oneof"`
}

type Message_PlayMoveUci struct {
	PlayMoveUci *PlayMoveUCI `protobuf:"bytes,24,opt,name=play_move_uci,json=playMoveUci,proto3,oneof"`
}

type Message_ReceiveMove struct {
	ReceiveMove *ReceiveMove `protobuf:"bytes,25,opt,name=receive_move,json=receiveMove,proto3,oneof"`
}

type Message_GameFinished struct {
	GameFinished *GameFinished `protobuf:"bytes,26,opt,name=game_finished,json=gameFinished,proto3,oneof"`
}

type Message_Echo struct {
	Echo *Echo `protobuf:"bytes,69,opt,name=echo,proto3,oneof"`
}

func (*Message_Problem) isMessage_Event() {}

func (*Message_Latency) isMessage_Event() {}

func (*Message_Heartbeat) isMessage_Event() {}

func (*Message_LeaveTab) isMessage_Event() {}

func (*Message_LeaveSite) isMessage_Event() {}

func (*Message_ClientConnected) isMessage_Event() {}

func (*Message_ClientDisconnected) isMessage_Event() {}

func (*Message_RequestInitialChannels) isMessage_Event() {}

func (*Message_InitialChannels) isMessage_Event() {}

func (*Message_RequestChannelsInfo) isMessage_Event() {}

func (*Message_PresenceChanged) isMessage_Event() {}

func (*Message_SeekGame) isMessage_Event() {}

func (*Message_CancelSeekGame) isMessage_Event() {}

func (*Message_HubInfo) isMessage_Event() {}

func (*Message_MatchFound) isMessage_Event() {}

func (*Message_GameAbort) isMessage_Event() {}

func (*Message_GameResign) isMessage_Event() {}

func (*Message_GameOfferDraw) isMessage_Event() {}

func (*Message_GameAcceptDraw) isMessage_Event() {}

func (*Message_GameDeclineDraw) isMessage_Event() {}

func (*Message_GameChat) isMessage_Event() {}

func (*Message_GameChatReceive) isMessage_Event() {}

func (*Message_GameChatRetrieve) isMessage_Event() {}

func (*Message_PlayMoveUci) isMessage_Event() {}

func (*Message_ReceiveMove) isMessage_Event() {}

func (*Message_GameFinished) isMessage_Event() {}

func (*Message_Echo) isMessage_Event() {}

// Echo is just for testing
type Echo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Echo) Reset() {
	*x = Echo{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{2}
}

func (x *Echo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat is when client sends pong to signal heartbeat
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Guest         bool                   `protobuf:"varint,3,opt,name=guest,proto3" json:"guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Heartbeat) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *Heartbeat) GetGuest() bool {
	if x != nil {
		return x.Guest
	}
	return false
}

// LeaveTab is when user leaves a tab (one conn)
type LeaveTab struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Guest         bool                   `protobuf:"varint,3,opt,name=guest,proto3" json:"guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveTab) Reset() {
	*x = LeaveTab{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveTab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTab) ProtoMessage() {}

func (x *LeaveTab) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTab.ProtoReflect.Descriptor instead.
func (*LeaveTab) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveTab) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveTab) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *LeaveTab) GetGuest() bool {
	if x != nil {
		return x.Guest
	}
	return false
}

// LeaveSite is when user leaves and has no conns anymore (all tabs closed)
type LeaveSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Guest         bool                   `protobuf:"varint,3,opt,name=guest,proto3" json:"guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSite) Reset() {
	*x = LeaveSite{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSite) ProtoMessage() {}

func (x *LeaveSite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSite.ProtoReflect.Descriptor instead.
func (*LeaveSite) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveSite) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveSite) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *LeaveSite) GetGuest() bool {
	if x != nil {
		return x.Guest
	}
	return false
}

// Latency is avg latency measured
type Latency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatencyMs     int32                  `protobuf:"varint,1,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Latency) Reset() {
	*x = Latency{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Latency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Latency) ProtoMessage() {}

func (x *Latency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Latency.ProtoReflect.Descriptor instead.
func (*Latency) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{6}
}

func (x *Latency) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// Problem is the websocket error
type Problem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{7}
}

func (x *Problem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ClientConnected signals that client connected
type ClientConnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConnected) Reset() {
	*x = ClientConnected{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnected) ProtoMessage() {}

func (x *ClientConnected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnected.ProtoReflect.Descriptor instead.
func (*ClientConnected) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{8}
}

func (x *ClientConnected) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ClientDisconnected signals that client disconnected
type ClientDisconnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDisconnected) Reset() {
	*x = ClientDisconnected{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnected) ProtoMessage() {}

func (x *ClientDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnected.ProtoReflect.Descriptor instead.
func (*ClientDisconnected) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{9}
}

func (x *ClientDisconnected) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RequestInitialChannels requests initial channels that the user belongs to (e.g. ["lobby", "lobby.chat"])
type RequestInitialChannels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Guest         bool                   `protobuf:"varint,3,opt,name=guest,proto3" json:"guest,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInitialChannels) Reset() {
	*x = RequestInitialChannels{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInitialChannels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInitialChannels) ProtoMessage() {}

func (x *RequestInitialChannels) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInitialChannels.ProtoReflect.Descriptor instead.
func (*RequestInitialChannels) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{10}
}

func (x *RequestInitialChannels) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestInitialChannels) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *RequestInitialChannels) GetGuest() bool {
	if x != nil {
		return x.Guest
	}
	return false
}

func (x *RequestInitialChannels) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// InitialChannels is the user initial channels
type InitialChannels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []string               `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialChannels) Reset() {
	*x = InitialChannels{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialChannels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialChannels) ProtoMessage() {}

func (x *InitialChannels) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialChannels.ProtoReflect.Descriptor instead.
func (*InitialChannels) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{11}
}

func (x *InitialChannels) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

// RequestChannelsInfo requests backend to send some data for initial channels
// e.g. users in lobby want to see active games, lobby.chat want lobby chat history, if in gametv, they want gamestate and move history etc.
type RequestChannelsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Guest         bool                   `protobuf:"varint,3,opt,name=guest,proto3" json:"guest,omitempty"`
	Channels      []string               `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestChannelsInfo) Reset() {
	*x = RequestChannelsInfo{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestChannelsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestChannelsInfo) ProtoMessage() {}

func (x *RequestChannelsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestChannelsInfo.ProtoReflect.Descriptor instead.
func (*RequestChannelsInfo) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{12}
}

func (x *RequestChannelsInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestChannelsInfo) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *RequestChannelsInfo) GetGuest() bool {
	if x != nil {
		return x.Guest
	}
	return false
}

func (x *RequestChannelsInfo) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

// PresenceChanged notifes that presence has changed
type PresenceChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Channels      []string               `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceChanged) Reset() {
	*x = PresenceChanged{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceChanged) ProtoMessage() {}

func (x *PresenceChanged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceChanged.ProtoReflect.Descriptor instead.
func (*PresenceChanged) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{13}
}

func (x *PresenceChanged) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceChanged) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PresenceChanged) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

// Clocks is white and black game clock
type Clocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	White         *durationpb.Duration   `protobuf:"bytes,1,opt,name=white,proto3" json:"white,omitempty"`
	Black         *durationpb.Duration   `protobuf:"bytes,2,opt,name=black,proto3" json:"black,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clocks) Reset() {
	*x = Clocks{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clocks) ProtoMessage() {}

func (x *Clocks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clocks.ProtoReflect.Descriptor instead.
func (*Clocks) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{14}
}

func (x *Clocks) GetWhite() *durationpb.Duration {
	if x != nil {
		return x.White
	}
	return nil
}

func (x *Clocks) GetBlack() *durationpb.Duration {
	if x != nil {
		return x.Black
	}
	return nil
}

// SeekGame is searching for a game
type SeekGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeControl   *GameTimeControl       `protobuf:"bytes,1,opt,name=time_control,json=timeControl,proto3" json:"time_control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeekGame) Reset() {
	*x = SeekGame{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekGame) ProtoMessage() {}

func (x *SeekGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekGame.ProtoReflect.Descriptor instead.
func (*SeekGame) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{15}
}

func (x *SeekGame) GetTimeControl() *GameTimeControl {
	if x != nil {
		return x.TimeControl
	}
	return nil
}

// CancelSeekGame cancels the game search
type CancelSeekGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeControl   *GameTimeControl       `protobuf:"bytes,1,opt,name=time_control,json=timeControl,proto3" json:"time_control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSeekGame) Reset() {
	*x = CancelSeekGame{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSeekGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSeekGame) ProtoMessage() {}

func (x *CancelSeekGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSeekGame.ProtoReflect.Descriptor instead.
func (*CancelSeekGame) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{16}
}

func (x *CancelSeekGame) GetTimeControl() *GameTimeControl {
	if x != nil {
		return x.TimeControl
	}
	return nil
}

// HubInfo is hub information
type HubInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         int32                  `protobuf:"varint,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	Playing       int32                  `protobuf:"varint,2,opt,name=playing,proto3" json:"playing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubInfo) Reset() {
	*x = HubInfo{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubInfo) ProtoMessage() {}

func (x *HubInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubInfo.ProtoReflect.Descriptor instead.
func (*HubInfo) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{17}
}

func (x *HubInfo) GetLobby() int32 {
	if x != nil {
		return x.Lobby
	}
	return 0
}

func (x *HubInfo) GetPlaying() int32 {
	if x != nil {
		return x.Playing
	}
	return 0
}

// OpponentInfo is info about opponent
type OpponentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,10,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Rating        int32                  `protobuf:"varint,11,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpponentInfo) Reset() {
	*x = OpponentInfo{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpponentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpponentInfo) ProtoMessage() {}

func (x *OpponentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpponentInfo.ProtoReflect.Descriptor instead.
func (*OpponentInfo) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{18}
}

func (x *OpponentInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OpponentInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *OpponentInfo) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

// HistoryMove is the move played
type HistoryMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uci           string                 `protobuf:"bytes,1,opt,name=uci,proto3" json:"uci,omitempty"`
	San           string                 `protobuf:"bytes,2,opt,name=san,proto3" json:"san,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryMove) Reset() {
	*x = HistoryMove{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryMove) ProtoMessage() {}

func (x *HistoryMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryMove.ProtoReflect.Descriptor instead.
func (*HistoryMove) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{19}
}

func (x *HistoryMove) GetUci() string {
	if x != nil {
		return x.Uci
	}
	return ""
}

func (x *HistoryMove) GetSan() string {
	if x != nil {
		return x.San
	}
	return ""
}

// HistoryMoveInfo holds info about the move
type HistoryMoveInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fen           string                 `protobuf:"bytes,1,opt,name=fen,proto3" json:"fen,omitempty"`
	PlayedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=played_at,json=playedAt,proto3,oneof" json:"played_at,omitempty"`
	Move          *HistoryMove           `protobuf:"bytes,3,opt,name=move,proto3,oneof" json:"move,omitempty"`
	Check         bool                   `protobuf:"varint,4,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryMoveInfo) Reset() {
	*x = HistoryMoveInfo{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryMoveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryMoveInfo) ProtoMessage() {}

func (x *HistoryMoveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryMoveInfo.ProtoReflect.Descriptor instead.
func (*HistoryMoveInfo) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{20}
}

func (x *HistoryMoveInfo) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *HistoryMoveInfo) GetPlayedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PlayedAt
	}
	return nil
}

func (x *HistoryMoveInfo) GetMove() *HistoryMove {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *HistoryMoveInfo) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

// MatchFound signals that the game was found
type MatchFound struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GameId             int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameState          GameState              `protobuf:"varint,3,opt,name=game_state,json=gameState,proto3,enum=pb.GameState" json:"game_state,omitempty"`
	Color              Color                  `protobuf:"varint,4,opt,name=color,proto3,enum=pb.Color" json:"color,omitempty"`
	Fen                string                 `protobuf:"bytes,5,opt,name=fen,proto3" json:"fen,omitempty"`
	Ply                uint32                 `protobuf:"varint,6,opt,name=ply,proto3" json:"ply,omitempty"`
	Clocks             *Clocks                `protobuf:"bytes,7,opt,name=clocks,proto3" json:"clocks,omitempty"`
	LegalMoves         []string               `protobuf:"bytes,8,rep,name=legal_moves,json=legalMoves,proto3" json:"legal_moves,omitempty"`
	TimeControl        *GameTimeControl       `protobuf:"bytes,9,opt,name=time_control,json=timeControl,proto3" json:"time_control,omitempty"`
	OpponentInfo       *OpponentInfo          `protobuf:"bytes,10,opt,name=opponent_info,json=opponentInfo,proto3,oneof" json:"opponent_info,omitempty"`
	ReconnectTimeoutMs int64                  `protobuf:"varint,11,opt,name=reconnect_timeout_ms,json=reconnectTimeoutMs,proto3" json:"reconnect_timeout_ms,omitempty"`
	FirstMoveTimeoutMs int64                  `protobuf:"varint,12,opt,name=first_move_timeout_ms,json=firstMoveTimeoutMs,proto3" json:"first_move_timeout_ms,omitempty"`
	HistoryMoveInfos   []*HistoryMoveInfo     `protobuf:"bytes,13,rep,name=history_move_infos,json=historyMoveInfos,proto3" json:"history_move_infos,omitempty"`
	StartTime          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{21}
}

func (x *MatchFound) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *MatchFound) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MatchFound) GetGameState() GameState {
	if x != nil {
		return x.GameState
	}
	return GameState_GAME_STATE_UNSPECIFIED
}

func (x *MatchFound) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *MatchFound) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *MatchFound) GetPly() uint32 {
	if x != nil {
		return x.Ply
	}
	return 0
}

func (x *MatchFound) GetClocks() *Clocks {
	if x != nil {
		return x.Clocks
	}
	return nil
}

func (x *MatchFound) GetLegalMoves() []string {
	if x != nil {
		return x.LegalMoves
	}
	return nil
}

func (x *MatchFound) GetTimeControl() *GameTimeControl {
	if x != nil {
		return x.TimeControl
	}
	return nil
}

func (x *MatchFound) GetOpponentInfo() *OpponentInfo {
	if x != nil {
		return x.OpponentInfo
	}
	return nil
}

func (x *MatchFound) GetReconnectTimeoutMs() int64 {
	if x != nil {
		return x.ReconnectTimeoutMs
	}
	return 0
}

func (x *MatchFound) GetFirstMoveTimeoutMs() int64 {
	if x != nil {
		return x.FirstMoveTimeoutMs
	}
	return 0
}

func (x *MatchFound) GetHistoryMoveInfos() []*HistoryMoveInfo {
	if x != nil {
		return x.HistoryMoveInfos
	}
	return nil
}

func (x *MatchFound) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// GameAbort is game abort request
type GameAbort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAbort) Reset() {
	*x = GameAbort{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAbort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAbort) ProtoMessage() {}

func (x *GameAbort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAbort.ProtoReflect.Descriptor instead.
func (*GameAbort) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{22}
}

// GameResign is game resign request
type GameResign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResign) Reset() {
	*x = GameResign{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResign) ProtoMessage() {}

func (x *GameResign) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResign.ProtoReflect.Descriptor instead.
func (*GameResign) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{23}
}

// GameOfferDraw is draw offer request
type GameOfferDraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOfferDraw) Reset() {
	*x = GameOfferDraw{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOfferDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOfferDraw) ProtoMessage() {}

func (x *GameOfferDraw) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOfferDraw.ProtoReflect.Descriptor instead.
func (*GameOfferDraw) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{24}
}

// GameDeclineDraw is draw declined
type GameDeclineDraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameDeclineDraw) Reset() {
	*x = GameDeclineDraw{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameDeclineDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDeclineDraw) ProtoMessage() {}

func (x *GameDeclineDraw) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDeclineDraw.ProtoReflect.Descriptor instead.
func (*GameDeclineDraw) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{25}
}

// GameAcceptDraw is accepting the draw offer
type GameAcceptDraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAcceptDraw) Reset() {
	*x = GameAcceptDraw{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAcceptDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAcceptDraw) ProtoMessage() {}

func (x *GameAcceptDraw) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAcceptDraw.ProtoReflect.Descriptor instead.
func (*GameAcceptDraw) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{26}
}

// GameChat is the game chat
type GameChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameChat) Reset() {
	*x = GameChat{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameChat) ProtoMessage() {}

func (x *GameChat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameChat.ProtoReflect.Descriptor instead.
func (*GameChat) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{27}
}

func (x *GameChat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GameChatReceive is xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
type GameChatReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameChatReceive) Reset() {
	*x = GameChatReceive{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameChatReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameChatReceive) ProtoMessage() {}

func (x *GameChatReceive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameChatReceive.ProtoReflect.Descriptor instead.
func (*GameChatReceive) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{28}
}

func (x *GameChatReceive) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GameChatReceive) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameChatReceive) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GameChatRetrieve is xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
type GameChatRetrieve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameChat      []*GameChatReceive     `protobuf:"bytes,1,rep,name=game_chat,json=gameChat,proto3" json:"game_chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameChatRetrieve) Reset() {
	*x = GameChatRetrieve{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameChatRetrieve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameChatRetrieve) ProtoMessage() {}

func (x *GameChatRetrieve) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameChatRetrieve.ProtoReflect.Descriptor instead.
func (*GameChatRetrieve) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{29}
}

func (x *GameChatRetrieve) GetGameChat() []*GameChatReceive {
	if x != nil {
		return x.GameChat
	}
	return nil
}

// PlayMoveUCI plays a game move
type PlayMoveUCI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          string                 `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoveUCI) Reset() {
	*x = PlayMoveUCI{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoveUCI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoveUCI) ProtoMessage() {}

func (x *PlayMoveUCI) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoveUCI.ProtoReflect.Descriptor instead.
func (*PlayMoveUCI) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{30}
}

func (x *PlayMoveUCI) GetMove() string {
	if x != nil {
		return x.Move
	}
	return ""
}

// ReceiveMove receives the game move
type ReceiveMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uci           string                 `protobuf:"bytes,1,opt,name=uci,proto3" json:"uci,omitempty"`
	Lan           string                 `protobuf:"bytes,2,opt,name=lan,proto3" json:"lan,omitempty"`
	San           string                 `protobuf:"bytes,3,opt,name=san,proto3" json:"san,omitempty"`
	Fen           string                 `protobuf:"bytes,4,opt,name=fen,proto3" json:"fen,omitempty"`
	Ply           uint32                 `protobuf:"varint,5,opt,name=ply,proto3" json:"ply,omitempty"`
	Clocks        *Clocks                `protobuf:"bytes,6,opt,name=clocks,proto3" json:"clocks,omitempty"`
	LegalMoves    []string               `protobuf:"bytes,7,rep,name=legal_moves,json=legalMoves,proto3" json:"legal_moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMove) Reset() {
	*x = ReceiveMove{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMove) ProtoMessage() {}

func (x *ReceiveMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMove.ProtoReflect.Descriptor instead.
func (*ReceiveMove) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{31}
}

func (x *ReceiveMove) GetUci() string {
	if x != nil {
		return x.Uci
	}
	return ""
}

func (x *ReceiveMove) GetLan() string {
	if x != nil {
		return x.Lan
	}
	return ""
}

func (x *ReceiveMove) GetSan() string {
	if x != nil {
		return x.San
	}
	return ""
}

func (x *ReceiveMove) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *ReceiveMove) GetPly() uint32 {
	if x != nil {
		return x.Ply
	}
	return 0
}

func (x *ReceiveMove) GetClocks() *Clocks {
	if x != nil {
		return x.Clocks
	}
	return nil
}

func (x *ReceiveMove) GetLegalMoves() []string {
	if x != nil {
		return x.LegalMoves
	}
	return nil
}

// GameFinished signals the game is over
type GameFinished struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GameResult       GameResult             `protobuf:"varint,1,opt,name=game_result,json=gameResult,proto3,enum=pb.GameResult" json:"game_result,omitempty"`
	GameResultStatus GameResultStatus       `protobuf:"varint,2,opt,name=game_result_status,json=gameResultStatus,proto3,enum=pb.GameResultStatus" json:"game_result_status,omitempty"`
	GameState        GameState              `protobuf:"varint,3,opt,name=game_state,json=gameState,proto3,enum=pb.GameState" json:"game_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameFinished) Reset() {
	*x = GameFinished{}
	mi := &file_proto_juicer_juicer_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFinished) ProtoMessage() {}

func (x *GameFinished) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juicer_juicer_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFinished.ProtoReflect.Descriptor instead.
func (*GameFinished) Descriptor() ([]byte, []int) {
	return file_proto_juicer_juicer_proto_rawDescGZIP(), []int{32}
}

func (x *GameFinished) GetGameResult() GameResult {
	if x != nil {
		return x.GameResult
	}
	return GameResult_GAME_RESULT_UNSPECIFIED
}

func (x *GameFinished) GetGameResultStatus() GameResultStatus {
	if x != nil {
		return x.GameResultStatus
	}
	return GameResultStatus_GAME_RESULT_STATUS_UNSPECIFIED
}

func (x *GameFinished) GetGameState() GameState {
	if x != nil {
		return x.GameState
	}
	return GameState_GAME_STATE_UNSPECIFIED
}

var File_proto_juicer_juicer_proto protoreflect.FileDescriptor

const file_proto_juicer_juicer_proto_rawDesc = "" +
	"\n" +
	"\x19proto/juicer/juicer.proto\x12\x02pb\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"{\n" +
	"\x0fGameTimeControl\x12/\n" +
	"\x05clock\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05clock\x127\n" +
	"\tincrement\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\tincrement\"\x91\f\n" +
	"\aMessage\x12'\n" +
	"\aproblem\x18\x01 \x01(\v2\v.pb.ProblemH\x00R\aproblem\x12'\n" +
	"\alatency\x18\x02 \x01(\v2\v.pb.LatencyH\x00R\alatency\x12-\n" +
	"\theartbeat\x18\x03 \x01(\v2\r.pb.HeartbeatH\x00R\theartbeat\x12+\n" +
	"\tleave_tab\x18\x04 \x01(\v2\f.pb.LeaveTabH\x00R\bleaveTab\x12.\n" +
	"\n" +
	"leave_site\x18\x05 \x01(\v2\r.pb.LeaveSiteH\x00R\tleaveSite\x12@\n" +
	"\x10client_connected\x18\x06 \x01(\v2\x13.pb.ClientConnectedH\x00R\x0fclientConnected\x12I\n" +
	"\x13client_disconnected\x18\a \x01(\v2\x16.pb.ClientDisconnectedH\x00R\x12clientDisconnected\x12V\n" +
	"\x18request_initial_channels\x18\b \x01(\v2\x1a.pb.RequestInitialChannelsH\x00R\x16requestInitialChannels\x12@\n" +
	"\x10initial_channels\x18\t \x01(\v2\x13.pb.InitialChannelsH\x00R\x0finitialChannels\x12M\n" +
	"\x15request_channels_info\x18\n" +
	" \x01(\v2\x17.pb.RequestChannelsInfoH\x00R\x13requestChannelsInfo\x12@\n" +
	"\x10presence_changed\x18\v \x01(\v2\x13.pb.PresenceChangedH\x00R\x0fpresenceChanged\x12+\n" +
	"\tseek_game\x18\f \x01(\v2\f.pb.SeekGameH\x00R\bseekGame\x12>\n" +
	"\x10cancel_seek_game\x18\r \x01(\v2\x12.pb.CancelSeekGameH\x00R\x0ecancelSeekGame\x12(\n" +
	"\bhub_info\x18\x0e \x01(\v2\v.pb.HubInfoH\x00R\ahubInfo\x121\n" +
	"\vmatch_found\x18\x0f \x01(\v2\x0e.pb.MatchFoundH\x00R\n" +
	"matchFound\x12.\n" +
	"\n" +
	"game_abort\x18\x10 \x01(\v2\r.pb.GameAbortH\x00R\tgameAbort\x121\n" +
	"\vgame_resign\x18\x11 \x01(\v2\x0e.pb.GameResignH\x00R\n" +
	"gameResign\x12;\n" +
	"\x0fgame_offer_draw\x18\x12 \x01(\v2\x11.pb.GameOfferDrawH\x00R\rgameOfferDraw\x12>\n" +
	"\x10game_accept_draw\x18\x13 \x01(\v2\x12.pb.GameAcceptDrawH\x00R\x0egameAcceptDraw\x12A\n" +
	"\x11game_decline_draw\x18\x14 \x01(\v2\x13.pb.GameDeclineDrawH\x00R\x0fgameDeclineDraw\x12+\n" +
	"\tgame_chat\x18\x15 \x01(\v2\f.pb.GameChatH\x00R\bgameChat\x12A\n" +
	"\x11game_chat_receive\x18\x16 \x01(\v2\x13.pb.GameChatReceiveH\x00R\x0fgameChatReceive\x12D\n" +
	"\x12game_chat_retrieve\x18\x17 \x01(\v2\x14.pb.GameChatRetrieveH\x00R\x10gameChatRetrieve\x125\n" +
	"\rplay_move_uci\x18\x18 \x01(\v2\x0f.pb.PlayMoveUCIH\x00R\vplayMoveUci\x124\n" +
	"\freceive_move\x18\x19 \x01(\v2\x0f.pb.ReceiveMoveH\x00R\vreceiveMove\x127\n" +
	"\rgame_finished\x18\x1a \x01(\v2\x10.pb.GameFinishedH\x00R\fgameFinished\x12\x1e\n" +
	"\x04echo\x18E \x01(\v2\b.pb.EchoH\x00R\x04echoB\a\n" +
	"\x05event\" \n" +
	"\x04Echo\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"S\n" +
	"\tHeartbeat\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x14\n" +
	"\x05guest\x18\x03 \x01(\bR\x05guest\"R\n" +
	"\bLeaveTab\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x14\n" +
	"\x05guest\x18\x03 \x01(\bR\x05guest\"S\n" +
	"\tLeaveSite\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x14\n" +
	"\x05guest\x18\x03 \x01(\bR\x05guest\"(\n" +
	"\aLatency\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x01 \x01(\x05R\tlatencyMs\"#\n" +
	"\aProblem\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\x0fClientConnected\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12ClientDisconnected\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"t\n" +
	"\x16RequestInitialChannels\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x14\n" +
	"\x05guest\x18\x03 \x01(\bR\x05guest\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"-\n" +
	"\x0fInitialChannels\x12\x1a\n" +
	"\bchannels\x18\x01 \x03(\tR\bchannels\"y\n" +
	"\x13RequestChannelsInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x14\n" +
	"\x05guest\x18\x03 \x01(\bR\x05guest\x12\x1a\n" +
	"\bchannels\x18\x04 \x03(\tR\bchannels\"b\n" +
	"\x0fPresenceChanged\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bchannels\x18\x03 \x03(\tR\bchannels\"j\n" +
	"\x06Clocks\x12/\n" +
	"\x05white\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05white\x12/\n" +
	"\x05black\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05black\"B\n" +
	"\bSeekGame\x126\n" +
	"\ftime_control\x18\x01 \x01(\v2\x13.pb.GameTimeControlR\vtimeControl\"H\n" +
	"\x0eCancelSeekGame\x126\n" +
	"\ftime_control\x18\x01 \x01(\v2\x13.pb.GameTimeControlR\vtimeControl\"9\n" +
	"\aHubInfo\x12\x14\n" +
	"\x05lobby\x18\x01 \x01(\x05R\x05lobby\x12\x18\n" +
	"\aplaying\x18\x02 \x01(\x05R\aplaying\"a\n" +
	"\fOpponentInfo\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\n" +
	" \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06rating\x18\v \x01(\x05R\x06rating\"1\n" +
	"\vHistoryMove\x12\x10\n" +
	"\x03uci\x18\x01 \x01(\tR\x03uci\x12\x10\n" +
	"\x03san\x18\x02 \x01(\tR\x03san\"\xb8\x01\n" +
	"\x0fHistoryMoveInfo\x12\x10\n" +
	"\x03fen\x18\x01 \x01(\tR\x03fen\x12<\n" +
	"\tplayed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bplayedAt\x88\x01\x01\x12(\n" +
	"\x04move\x18\x03 \x01(\v2\x0f.pb.HistoryMoveH\x01R\x04move\x88\x01\x01\x12\x14\n" +
	"\x05check\x18\x04 \x01(\bR\x05checkB\f\n" +
	"\n" +
	"_played_atB\a\n" +
	"\x05_move\"\xdf\x04\n" +
	"\n" +
	"MatchFound\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\n" +
	"game_state\x18\x03 \x01(\x0e2\r.pb.GameStateR\tgameState\x12\x1f\n" +
	"\x05color\x18\x04 \x01(\x0e2\t.pb.ColorR\x05color\x12\x10\n" +
	"\x03fen\x18\x05 \x01(\tR\x03fen\x12\x10\n" +
	"\x03ply\x18\x06 \x01(\rR\x03ply\x12\"\n" +
	"\x06clocks\x18\a \x01(\v2\n" +
	".pb.ClocksR\x06clocks\x12\x1f\n" +
	"\vlegal_moves\x18\b \x03(\tR\n" +
	"legalMoves\x126\n" +
	"\ftime_control\x18\t \x01(\v2\x13.pb.GameTimeControlR\vtimeControl\x12:\n" +
	"\ropponent_info\x18\n" +
	" \x01(\v2\x10.pb.OpponentInfoH\x00R\fopponentInfo\x88\x01\x01\x120\n" +
	"\x14reconnect_timeout_ms\x18\v \x01(\x03R\x12reconnectTimeoutMs\x121\n" +
	"\x15first_move_timeout_ms\x18\f \x01(\x03R\x12firstMoveTimeoutMs\x12A\n" +
	"\x12history_move_infos\x18\r \x03(\v2\x13.pb.HistoryMoveInfoR\x10historyMoveInfos\x129\n" +
	"\n" +
	"start_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tstartTimeB\x10\n" +
	"\x0e_opponent_info\"\v\n" +
	"\tGameAbort\"\f\n" +
	"\n" +
	"GameResign\"\x0f\n" +
	"\rGameOfferDraw\"\x11\n" +
	"\x0fGameDeclineDraw\"\x10\n" +
	"\x0eGameAcceptDraw\"$\n" +
	"\bGameChat\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"T\n" +
	"\x0fGameChatReceive\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"D\n" +
	"\x10GameChatRetrieve\x120\n" +
	"\tgame_chat\x18\x01 \x03(\v2\x13.pb.GameChatReceiveR\bgameChat\"!\n" +
	"\vPlayMoveUCI\x12\x12\n" +
	"\x04move\x18\x01 \x01(\tR\x04move\"\xac\x01\n" +
	"\vReceiveMove\x12\x10\n" +
	"\x03uci\x18\x01 \x01(\tR\x03uci\x12\x10\n" +
	"\x03lan\x18\x02 \x01(\tR\x03lan\x12\x10\n" +
	"\x03san\x18\x03 \x01(\tR\x03san\x12\x10\n" +
	"\x03fen\x18\x04 \x01(\tR\x03fen\x12\x10\n" +
	"\x03ply\x18\x05 \x01(\rR\x03ply\x12\"\n" +
	"\x06clocks\x18\x06 \x01(\v2\n" +
	".pb.ClocksR\x06clocks\x12\x1f\n" +
	"\vlegal_moves\x18\a \x03(\tR\n" +
	"legalMoves\"\xb1\x01\n" +
	"\fGameFinished\x12/\n" +
	"\vgame_result\x18\x01 \x01(\x0e2\x0e.pb.GameResultR\n" +
	"gameResult\x12B\n" +
	"\x12game_result_status\x18\x02 \x01(\x0e2\x14.pb.GameResultStatusR\x10gameResultStatus\x12,\n" +
	"\n" +
	"game_state\x18\x03 \x01(\x0e2\r.pb.GameStateR\tgameState*@\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCOLOR_WHITE\x10\x01\x12\x0f\n" +
	"\vCOLOR_BLACK\x10\x02*\x8f\x02\n" +
	"\vGameVariant\x12\x1c\n" +
	"\x18GAME_VARIANT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15GAME_VARIANT_STANDARD\x10\x01\x12\x17\n" +
	"\x13GAME_VARIANT_ATOMIC\x10\x02\x12\x1b\n" +
	"\x17GAME_VARIANT_CRAZYHOUSE\x10\x03\x12\x19\n" +
	"\x15GAME_VARIANT_CHESS960\x10\x04\x12!\n" +
	"\x1dGAME_VARIANT_KING_OF_THE_HILL\x10\x05\x12\x1c\n" +
	"\x18GAME_VARIANT_THREE_CHECK\x10\x06\x12\x16\n" +
	"\x12GAME_VARIANT_HORDE\x10\a\x12\x1d\n" +
	"\x19GAME_VARIANT_RACING_KINGS\x10\b*\x8c\x01\n" +
	"\fGameTimeKind\x12\x1e\n" +
	"\x1aGAME_TIME_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GAME_TIME_KIND_REALTIME\x10\x01\x12!\n" +
	"\x1dGAME_TIME_KIND_CORRESPONDENCE\x10\x02\x12\x1c\n" +
	"\x18GAME_TIME_KIND_UNLIMITED\x10\x03*\xd7\x01\n" +
	"\x10GameTimeCategory\x12\"\n" +
	"\x1eGAME_TIME_CATEGORY_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eGAME_TIME_CATEGORY_HYPERBULLET\x10\x01\x12\x1d\n" +
	"\x19GAME_TIME_CATEGORY_BULLET\x10\x02\x12\x1c\n" +
	"\x18GAME_TIME_CATEGORY_BLITZ\x10\x03\x12\x1c\n" +
	"\x18GAME_TIME_CATEGORY_RAPID\x10\x04\x12 \n" +
	"\x1cGAME_TIME_CATEGORY_CLASSICAL\x10\x05*\x92\x01\n" +
	"\n" +
	"GameResult\x12\x1b\n" +
	"\x17GAME_RESULT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15GAME_RESULT_WHITE_WON\x10\x01\x12\x19\n" +
	"\x15GAME_RESULT_BLACK_WON\x10\x02\x12\x14\n" +
	"\x10GAME_RESULT_DRAW\x10\x03\x12\x1b\n" +
	"\x17GAME_RESULT_INTERRUPTED\x10\x04*\xca\x04\n" +
	"\x10GameResultStatus\x12\"\n" +
	"\x1eGAME_RESULT_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cGAME_RESULT_STATUS_CHECKMATE\x10\x01\x12,\n" +
	"(GAME_RESULT_STATUS_INSUFFICIENT_MATERIAL\x10\x02\x12+\n" +
	"'GAME_RESULT_STATUS_THREEFOLD_REPETITION\x10\x03\x12*\n" +
	"&GAME_RESULT_STATUS_FIVEFOLD_REPETITION\x10\x04\x12&\n" +
	"\"GAME_RESULT_STATUS_FIFTY_MOVE_RULE\x10\x05\x12,\n" +
	"(GAME_RESULT_STATUS_SEVENTYFIVE_MOVE_RULE\x10\x06\x12 \n" +
	"\x1cGAME_RESULT_STATUS_STALEMATE\x10\a\x12\"\n" +
	"\x1eGAME_RESULT_STATUS_RESIGNATION\x10\b\x12\"\n" +
	"\x1eGAME_RESULT_STATUS_DRAW_AGREED\x10\t\x12\x1e\n" +
	"\x1aGAME_RESULT_STATUS_FLAGGED\x10\n" +
	"\x12#\n" +
	"\x1fGAME_RESULT_STATUS_ADJUDICATION\x10\v\x12 \n" +
	"\x1cGAME_RESULT_STATUS_TIMED_OUT\x10\f\x12\x1e\n" +
	"\x1aGAME_RESULT_STATUS_ABORTED\x10\r\x12\"\n" +
	"\x1eGAME_RESULT_STATUS_INTERRUPTED\x10\x0e*\xab\x01\n" +
	"\tGameState\x12\x1a\n" +
	"\x16GAME_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fGAME_STATE_IDLE\x10\x01\x12\x1c\n" +
	"\x18GAME_STATE_WAITING_START\x10\x02\x12\x1a\n" +
	"\x16GAME_STATE_IN_PROGRESS\x10\x03\x12\x17\n" +
	"\x13GAME_STATE_FINISHED\x10\x04\x12\x1a\n" +
	"\x16GAME_STATE_INTERRUPTED\x10\x05*\x87\x01\n" +
	"\x0eGameSideChoice\x12 \n" +
	"\x1cGAME_SIDE_CHOICE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GAME_SIDE_CHOICE_RANDOM\x10\x01\x12\x1a\n" +
	"\x16GAME_SIDE_CHOICE_WHITE\x10\x02\x12\x1a\n" +
	"\x16GAME_SIDE_CHOICE_BLACK\x10\x03B\x1eZ\x1cgithub.com/dankobg/juicer/pbb\x06proto3"

var (
	file_proto_juicer_juicer_proto_rawDescOnce sync.Once
	file_proto_juicer_juicer_proto_rawDescData []byte
)

func file_proto_juicer_juicer_proto_rawDescGZIP() []byte {
	file_proto_juicer_juicer_proto_rawDescOnce.Do(func() {
		file_proto_juicer_juicer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_juicer_juicer_proto_rawDesc), len(file_proto_juicer_juicer_proto_rawDesc)))
	})
	return file_proto_juicer_juicer_proto_rawDescData
}

var file_proto_juicer_juicer_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_proto_juicer_juicer_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_juicer_juicer_proto_goTypes = []any{
	(Color)(0),                     // 0: pb.Color
	(GameVariant)(0),               // 1: pb.GameVariant
	(GameTimeKind)(0),              // 2: pb.GameTimeKind
	(GameTimeCategory)(0),          // 3: pb.GameTimeCategory
	(GameResult)(0),                // 4: pb.GameResult
	(GameResultStatus)(0),          // 5: pb.GameResultStatus
	(GameState)(0),                 // 6: pb.GameState
	(GameSideChoice)(0),            // 7: pb.GameSideChoice
	(*GameTimeControl)(nil),        // 8: pb.GameTimeControl
	(*Message)(nil),                // 9: pb.Message
	(*Echo)(nil),                   // 10: pb.Echo
	(*Heartbeat)(nil),              // 11: pb.Heartbeat
	(*LeaveTab)(nil),               // 12: pb.LeaveTab
	(*LeaveSite)(nil),              // 13: pb.LeaveSite
	(*Latency)(nil),                // 14: pb.Latency
	(*Problem)(nil),                // 15: pb.Problem
	(*ClientConnected)(nil),        // 16: pb.ClientConnected
	(*ClientDisconnected)(nil),     // 17: pb.ClientDisconnected
	(*RequestInitialChannels)(nil), // 18: pb.RequestInitialChannels
	(*InitialChannels)(nil),        // 19: pb.InitialChannels
	(*RequestChannelsInfo)(nil),    // 20: pb.RequestChannelsInfo
	(*PresenceChanged)(nil),        // 21: pb.PresenceChanged
	(*Clocks)(nil),                 // 22: pb.Clocks
	(*SeekGame)(nil),               // 23: pb.SeekGame
	(*CancelSeekGame)(nil),         // 24: pb.CancelSeekGame
	(*HubInfo)(nil),                // 25: pb.HubInfo
	(*OpponentInfo)(nil),           // 26: pb.OpponentInfo
	(*HistoryMove)(nil),            // 27: pb.HistoryMove
	(*HistoryMoveInfo)(nil),        // 28: pb.HistoryMoveInfo
	(*MatchFound)(nil),             // 29: pb.MatchFound
	(*GameAbort)(nil),              // 30: pb.GameAbort
	(*GameResign)(nil),             // 31: pb.GameResign
	(*GameOfferDraw)(nil),          // 32: pb.GameOfferDraw
	(*GameDeclineDraw)(nil),        // 33: pb.GameDeclineDraw
	(*GameAcceptDraw)(nil),         // 34: pb.GameAcceptDraw
	(*GameChat)(nil),               // 35: pb.GameChat
	(*GameChatReceive)(nil),        // 36: pb.GameChatReceive
	(*GameChatRetrieve)(nil),       // 37: pb.GameChatRetrieve
	(*PlayMoveUCI)(nil),            // 38: pb.PlayMoveUCI
	(*ReceiveMove)(nil),            // 39: pb.ReceiveMove
	(*GameFinished)(nil),           // 40: pb.GameFinished
	(*durationpb.Duration)(nil),    // 41: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),  // 42: google.protobuf.Timestamp
}
var file_proto_juicer_juicer_proto_depIdxs = []int32{
	41, // 0: pb.GameTimeControl.clock:type_name -> google.protobuf.Duration
	41, // 1: pb.GameTimeControl.increment:type_name -> google.protobuf.Duration
	15, // 2: pb.Message.problem:type_name -> pb.Problem
	14, // 3: pb.Message.latency:type_name -> pb.Latency
	11, // 4: pb.Message.heartbeat:type_name -> pb.Heartbeat
	12, // 5: pb.Message.leave_tab:type_name -> pb.LeaveTab
	13, // 6: pb.Message.leave_site:type_name -> pb.LeaveSite
	16, // 7: pb.Message.client_connected:type_name -> pb.ClientConnected
	17, // 8: pb.Message.client_disconnected:type_name -> pb.ClientDisconnected
	18, // 9: pb.Message.request_initial_channels:type_name -> pb.RequestInitialChannels
	19, // 10: pb.Message.initial_channels:type_name -> pb.InitialChannels
	20, // 11: pb.Message.request_channels_info:type_name -> pb.RequestChannelsInfo
	21, // 12: pb.Message.presence_changed:type_name -> pb.PresenceChanged
	23, // 13: pb.Message.seek_game:type_name -> pb.SeekGame
	24, // 14: pb.Message.cancel_seek_game:type_name -> pb.CancelSeekGame
	25, // 15: pb.Message.hub_info:type_name -> pb.HubInfo
	29, // 16: pb.Message.match_found:type_name -> pb.MatchFound
	30, // 17: pb.Message.game_abort:type_name -> pb.GameAbort
	31, // 18: pb.Message.game_resign:type_name -> pb.GameResign
	32, // 19: pb.Message.game_offer_draw:type_name -> pb.GameOfferDraw
	34, // 20: pb.Message.game_accept_draw:type_name -> pb.GameAcceptDraw
	33, // 21: pb.Message.game_decline_draw:type_name -> pb.GameDeclineDraw
	35, // 22: pb.Message.game_chat:type_name -> pb.GameChat
	36, // 23: pb.Message.game_chat_receive:type_name -> pb.GameChatReceive
	37, // 24: pb.Message.game_chat_retrieve:type_name -> pb.GameChatRetrieve
	38, // 25: pb.Message.play_move_uci:type_name -> pb.PlayMoveUCI
	39, // 26: pb.Message.receive_move:type_name -> pb.ReceiveMove
	40, // 27: pb.Message.game_finished:type_name -> pb.GameFinished
	10, // 28: pb.Message.echo:type_name -> pb.Echo
	41, // 29: pb.Clocks.white:type_name -> google.protobuf.Duration
	41, // 30: pb.Clocks.black:type_name -> google.protobuf.Duration
	8,  // 31: pb.SeekGame.time_control:type_name -> pb.GameTimeControl
	8,  // 32: pb.CancelSeekGame.time_control:type_name -> pb.GameTimeControl
	42, // 33: pb.HistoryMoveInfo.played_at:type_name -> google.protobuf.Timestamp
	27, // 34: pb.HistoryMoveInfo.move:type_name -> pb.HistoryMove
	6,  // 35: pb.MatchFound.game_state:type_name -> pb.GameState
	0,  // 36: pb.MatchFound.color:type_name -> pb.Color
	22, // 37: pb.MatchFound.clocks:type_name -> pb.Clocks
	8,  // 38: pb.MatchFound.time_control:type_name -> pb.GameTimeControl
	26, // 39: pb.MatchFound.opponent_info:type_name -> pb.OpponentInfo
	28, // 40: pb.MatchFound.history_move_infos:type_name -> pb.HistoryMoveInfo
	42, // 41: pb.MatchFound.start_time:type_name -> google.protobuf.Timestamp
	36, // 42: pb.GameChatRetrieve.game_chat:type_name -> pb.GameChatReceive
	22, // 43: pb.ReceiveMove.clocks:type_name -> pb.Clocks
	4,  // 44: pb.GameFinished.game_result:type_name -> pb.GameResult
	5,  // 45: pb.GameFinished.game_result_status:type_name -> pb.GameResultStatus
	6,  // 46: pb.GameFinished.game_state:type_name -> pb.GameState
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_proto_juicer_juicer_proto_init() }
func file_proto_juicer_juicer_proto_init() {
	if File_proto_juicer_juicer_proto != nil {
		return
	}
	file_proto_juicer_juicer_proto_msgTypes[1].OneofWrappers = []any{
		(*Message_Problem)(nil),
		(*Message_Latency)(nil),
		(*Message_Heartbeat)(nil),
		(*Message_LeaveTab)(nil),
		(*Message_LeaveSite)(nil),
		(*Message_ClientConnected)(nil),
		(*Message_ClientDisconnected)(nil),
		(*Message_RequestInitialChannels)(nil),
		(*Message_InitialChannels)(nil),
		(*Message_RequestChannelsInfo)(nil),
		(*Message_PresenceChanged)(nil),
		(*Message_SeekGame)(nil),
		(*Message_CancelSeekGame)(nil),
		(*Message_HubInfo)(nil),
		(*Message_MatchFound)(nil),
		(*Message_GameAbort)(nil),
		(*Message_GameResign)(nil),
		(*Message_GameOfferDraw)(nil),
		(*Message_GameAcceptDraw)(nil),
		(*Message_GameDeclineDraw)(nil),
		(*Message_GameChat)(nil),
		(*Message_GameChatReceive)(nil),
		(*Message_GameChatRetrieve)(nil),
		(*Message_PlayMoveUci)(nil),
		(*Message_ReceiveMove)(nil),
		(*Message_GameFinished)(nil),
		(*Message_Echo)(nil),
	}
	file_proto_juicer_juicer_proto_msgTypes[20].OneofWrappers = []any{}
	file_proto_juicer_juicer_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_juicer_juicer_proto_rawDesc), len(file_proto_juicer_juicer_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_juicer_juicer_proto_goTypes,
		DependencyIndexes: file_proto_juicer_juicer_proto_depIdxs,
		EnumInfos:         file_proto_juicer_juicer_proto_enumTypes,
		MessageInfos:      file_proto_juicer_juicer_proto_msgTypes,
	}.Build()
	File_proto_juicer_juicer_proto = out.File
	file_proto_juicer_juicer_proto_goTypes = nil
	file_proto_juicer_juicer_proto_depIdxs = nil
}
