apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: kratos-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: kratos-secret
    envs:
      - kratos-prod.env
