kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

generators:
  - kratos-prod-gen.yaml

namespace: prod

# namePrefix: prod-

configMapGenerator:
  - name: kratos-conf
    envs:
      - kratos-prod.conf
