---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-cert
  namespace: prod
spec:
  secretName: le-secret
  issuerRef:
    name: le-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - dankop.xyz
