---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kratos-courier
  namespace: default
  labels:
    app.kubernetes.io/name: kratos-courier
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kratos-courier
  serviceName: kratos-courier
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kratos-courier
    spec:
      containers:
        - name: kratos-courier
          image: oryd/kratos:v1.2.0
          imagePullPolicy: IfNotPresent
          args:
            - courier
            - watch
            - --config
            - /etc/config/kratos/kratos.yaml
          envFrom:
            - configMapRef:
                name: kratos-conf
            - secretRef:
                name: kratos-secret
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
          volumeMounts:
            - name: kratos-config
              mountPath: /etc/config/kratos
            - name: kratos-identity-schemas
              mountPath: /etc/config/kratos/schemas
            - name: kratos-oidc-schemas
              mountPath: /etc/config/kratos/oidc
            - name: kratos-hooks
              mountPath: /etc/config/kratos/hooks
            - name: kratos-imports
              mountPath: /etc/config/kratos/imports
            - name: kratos-courier-templates
              mountPath: /etc/config/kratos/courier-templates
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 100
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: kratos-config
          configMap:
            name: kratos-config
        - name: kratos-identity-schemas
          configMap:
            name: kratos-identity-schemas
        - name: kratos-oidc-schemas
          configMap:
            name: kratos-oidc-schemas
        - name: kratos-hooks
          configMap:
            name: kratos-hooks
        - name: kratos-imports
          configMap:
            name: kratos-imports
        - name: kratos-courier-templates
          configMap:
            name: kratos-courier-templates
      serviceAccountName: kratos
      automountServiceAccountToken: true
