---
apiVersion: v1
kind: Service
metadata:
  name: kratos
  labels:
    app.kubernetes.io/name: kratos
spec:
  ports:
    - name: kratos-public
      protocol: TCP
      port: 4433
      targetPort: 4433
    - name: kratos-admin
      protocol: TCP
      port: 4434
      targetPort: 4434
  selector:
    app.kubernetes.io/name: kratos
status:
  loadBalancer: {}
