kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  # - cert-manager.yaml
  # - cnpg-manifest.yaml
  - ns.yaml
  - cluster-issuer.yaml
  - certificate.yaml
  - https-mw.yaml
  # - traefik.yaml

generators:
  - tls-certs-secret-gen.yaml
