---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tls-certs-secret-gen
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: local-ca-secret
      namespace: cert-manager
    files:
      - certs/tls.key
      - certs/tls.crt
    type: kubernetes.io/tls
