apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ghcr-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: ghcr-secret
    files:
      - .dockerconfigjson
    type: kubernetes.io/dockerconfigjson
