kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - deploy.yaml
  - svc.yaml
  - sa.yaml
  - mw.yaml
  - ingress-route.yaml # @TODO: fix
  # - gateway-routes.yaml # @TODO: fix

generators:
  - ghcr-secret-gen.yaml
