kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - postgres-manifest.yaml

generators:
  - postgres-dev-gen.yaml

namespace: dev

# namePrefix: dev-

configMapGenerator:
  - name: postgres-conf
    envs:
      - postgres-dev.conf
