---
apiVersion: v1
kind: Service
metadata:
  name: pgsql-headless
  labels:
    app.kubernetes.io/name: pgsql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: primary
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql
  selector:
    app.kubernetes.io/name: pgsql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: primary
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  labels:
    app.kubernetes.io/name: pgsql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql
  selector:
    app.kubernetes.io/name: pgsql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: primary
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql
  labels:
    app.kubernetes.io/name: pgsql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  serviceName: pgsql-headless
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: pgsql
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/component: primary
  template:
    metadata:
      name: pgsql
      labels:
        app.kubernetes.io/name: pgsql
        app.kubernetes.io/instance: postgresql
        app.kubernetes.io/component: primary
    spec:
      serviceAccountName: default
      affinity:
        podAffinity: {}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: pgsql
                    app.kubernetes.io/instance: postgresql
                    app.kubernetes.io/component: primary
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity: {}

      securityContext:
        fsGroup: 1001
      hostNetwork: false
      hostIPC: false
      containers:
        - name: pgsql
          image: docker.io/bitnami/postgresql:15.3.0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          envFrom:
            - configMapRef:
                name: postgres-conf
            - secretRef:
                name: postgres-secret
          ports:
            - name: pgsql
              containerPort: 5432
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U $POSTGRES_USER -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U $POSTGRES_USER -h 127.0.0.1 -p 5432
          resources:
            limits: {}
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /bitnami/postgresql
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "4Gi"
