apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: postgres-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: postgres-secret
    envs:
      - postgres-dev.env
